### PR TITLE
Fix sacrifice self-death triggers

### LINKED ISSUE #12195: Creatures sacrificed  don't trigger their own death triggers
[[Industrial Advancement]]. I've noticed it several times. Here's an example of a log:

image

I sacrificed my [[Junji, the Midnight Sky]] and its death trigger did not trigger. Here's a pic of the board state:

image

### PR DESCRIPTION
**Pull request by alexander-novo**
Fixes #12195. Currently just tests. No clue what's going on, would appreciate thoughts.

### CODE REVIEW

**Comment by alexander-novo** [comment]
Curiously, the first test (sacrifice with [[Phyrexian Tower]]) passes, but not the second ([[Vivien on the Hunt]]).

Vivien's ability (and the ability from Industrial Advancement in the original issue) uses this code for sacrifice:

https://github.com/magefree/mage/blob/11e54fa367f702d74bcf18233d3a51bee02f122f/Mage.Sets/src/mage/cards/v/VivienOnTheHunt.java#L82-L84

Phyrexian Tower uses a `SacrificeTargetCost `:

https://github.com/magefree/mage/blob/11e54fa367f702d74bcf18233d3a51bee02f122f/Mage.Sets/src/mage/cards/p/PhyrexianTower.java#L34

Which in the end uses the same code to sacrifice:

https://github.com/magefree/mage/blob/11e54fa367f702d74bcf18233d3a51bee02f122f/Mage/src/main/java/mage/abilities/costs/common/SacrificeTargetCost.java#L71

So I don't know what's going on. Gonna try and use `git bisect`, because this is hopefully a more recent issue?

**Comment by alexander-novo** [comment]
Test fails as far back as 697c550, so this isn't actually anything new, just unnoticed.

**Comment by JayDi85** [comment]
First test was fie, second test was wrong. 

Correct tests (all pass with current source). If you catch bugs in real game with same commands then report here -- it can be related to GUI or AI bug:

``` java
package org.mage.test.cards.triggers.dies;

import mage.constants.PhaseStep;
import mage.constants.Zone;
import org.junit.Test;
import org.mage.test.player.TestPlayer;
import org.mage.test.serverside.base.CardTestPlayerBase;

/**
 * @author alexander-novo
 * <p>
 * Make sure sacrificed creatures trigger their own death abilities
 */
public class SacrificeDeathTriggersTest extends CardTestPlayerBase {

    static final String kokusho = "Kokusho, the Evening Star";

    @Test
    public void testSacrificeTriggersDiesAbility_NoChoices() {
        addCard(Zone.BATTLEFIELD, playerA, "Phyrexian Tower", 1); // {T}, Sacrifice a creature: Add {B}{B}.
        addCard(Zone.BATTLEFIELD, playerA, kokusho, 1); // When Kokusho, the Evening Star dies, each opponent loses 5 life. You gain life equal to the life lost this way.

        activateAbility(1, PhaseStep.PRECOMBAT_MAIN, playerA, "{T}, Sacrifice a creature: Add {B}{B}");
        setChoice(playerA, kokusho);

        checkStackObject("trigger", 1, PhaseStep.PRECOMBAT_MAIN, playerA, "When {this} dies,", 1);

        setStrictChooseMode(true);
        setStopAt(1, PhaseStep.BEGIN_COMBAT);
        execute();

        assertPermanentCount(playerA, kokusho, 0);
        assertLife(playerA, 25);
        assertLife(playerB, 15);
    }

    @Test
    public void testSacrificeTriggersDiesAbility_WithChoices() {
        addCard(Zone.BATTLEFIELD, playerA, "Vivien on the Hunt", 1); // +2: You may sacrifice a creature.
        addCard(Zone.BATTLEFIELD, playerA, kokusho, 1); // When Kokusho, the Evening Star dies, each opponent loses 5 life. You gain life equal to the life lost this way.

        activateAbility(1, PhaseStep.PRECOMBAT_MAIN, playerA, "+2: You may sacrifice a creature.");
        setChoice(playerA, kokusho); // sacrifice for +2
        addTarget(playerA, TestPlayer.TARGET_SKIP); // no selects from lib
        waitStackResolved(1, PhaseStep.PRECOMBAT_MAIN, 1);
        checkStackObject("trigger", 1, PhaseStep.PRECOMBAT_MAIN, playerA, "When {this} dies,", 1);

        setStrictChooseMode(true);
        setStopAt(1, PhaseStep.BEGIN_COMBAT);
        execute();

        assertPermanentCount(playerA, kokusho, 0);
        assertLife(playerA, 25);
        assertLife(playerB, 15);
    }
}
```

How-to write/debug tests -- use steps by steps approach:

1. Run without choice commands in strict mode to find first miss command:
shot_240502_070759

2. Enter first command and run again to find next miss - repeat until test done:
shot_240502_071007

3. Stack checks must be used carefully cause `checkXXX` commands runs immediately on priority (player/turn/step) and you must resolve stack objects one by one (first resolve will be activated ability, second resolve will be a trigger):
shot_240502_071356

**Comment by alexander-novo** [comment]
Oh you're absolutely right - woops. Forgot it wasn't a cost.

**Comment by alexander-novo** [comment]
Jaydi ended up with correct tests in #12195

**Pull request closed without merging**
