### PR TITLE
[LCI] Implement Tarrian's Journal // The Tomb of Aclazotz

### PR DESCRIPTION
**Pull request by Susucre**
Still WIP, the replacement effect to alter the spell/permanent is not working. Permission watcher / effect is set up properly.

There needs to be a creature type addition for the spell / permanent it becomes, and the added finality counter for the permanent. If someone got a good grasp of how to add those, I could use some guidance there.

### CODE REVIEW

**Comment by Susucre** [comment]
[[Tarrian's Journal]]

**Comment by jeffwadsworth** [comment]
I was messing around with this one, but got sidetracked at work.  Anyway, check this example for the permission.  https://github.com/magefree/mage/commit/898952515e1270544b0d1f7ba63e81f97d7f2dab

**Comment by jeffwadsworth** [comment]
It seems to work fine, but if not, it will be fixed.  Will check to see if you finish it up by tomorrow.
TheTomb

**Comment by Susucre** [comment]
Another dev did implement the card independently

**Pull request closed without merging**
