### PR TITLE
[DSC] Implement Giggling Skitterspike

### PR DESCRIPTION
**Pull request by Cguy7777**

### CODE REVIEW

**Comment by Grath** [comment]
Does this need to be a custom TriggeredAbility or could it be implemented with an OrTriggeredAbility like [Goldspan Dragon](https://github.com/magefree/mage/blob/master/Mage.Sets/src/mage/cards/g/GoldspanDragon.java)?

**Comment by Cguy7777** [comment]
It looks like it can use an OrTriggeredAbility, I must've missed that. Thank you.

**Review by Grath — APPROVED** [review]
That's a lot cleaner, nice.

**Comment by Grath** [comment]
Travis failure is unrelated, merging anyways.

**Pull request merged**
