### PR TITLE
Fixed Thousand-Year Storm and Mirari and added hint to Aetherflux Res…

### PR DESCRIPTION
**Pull request by jasc7636**
This addresses the issue of Thousand-Year Storm copying spells incorrectly or not at all #5698 #6076 and Mirari not copying stuff #5844 #6291 #6338

I reimplemented the Thousand-Year Storm ability to function simular to the Sentinel Tower abiliy. This fixes the error of only one copy of the card working properly in the deck and the other ones doing nothing.
With this change it now also calculates the right number of copies when:
Cast a Shock -> (with Thousand-Year Storm trigger on the stack) -> Narset's Reversal the Shock -> Cast the same Shock again
Previous to this change the Thousand-Year Storm trigger of the Shock at the beginning copied it 2 times instead of making no copies (as no spells have been cast before this turn)

I also replaced Miraris custom triggerd ability with ```SpellCastControllerTriggeredAbility``` due to the custom ability not working properly.

While doing this changes I noticed that Aetherflux Resovoir and Sentinel Tower are missing hints although it would be nice to have them here as well. I added hints simular to the one on Thousand Year-Storm.

### CODE REVIEW

**Comment by jasc7636** [comment]
Sorry for failing the CI check, it's one of my first contributions.

The problem is because of the ```ThousandYearStormWatcher``` class is not allowed to overwrite the copy method because it extends the ```Watcher``` class.
The default ```Watcher``` class copy method doesn't work here because it just makes a deep copy of the HashMap but not the Lists inside the HashMap.
Is there a clean solution for this?

**Comment by jasc7636** [comment]
I have read in the code a little bit deeper and modified the ```copy``` method in the ```Watcher``` class to correctly copy the ```ThousandYearStormWatcher``` class.
While doing this i found that the ```copy``` method contains some unreachable code:
https://github.com/magefree/mage/blob/47af865bc315ace0bc09ca2ce191552aebac57f8/Mage/src/main/java/mage/watchers/Watcher.java#L122-L130
The ```if``` is always false because ```valueType.getClass().getSimpleName()``` evaluates to ```Type```.
The second commit fixes that problem and implements some more tests to assure the right behavior.

**Comment by JayDi85** [comment]
@jasc7636 why it was deleted/close?

**Comment by jasc7636** [comment]
@JayDi85 I deleted it because I think splitting the fixes for the Thousand-Year Storm card and the copy method of the Watcher class makes sense.
I opened two new pull requests to split those topics from each other. 
One of them has the changes for the Watcher copy method #6644. Changing the Watcher copy method has a wide range of influence as it changes other subclasses as well and should be reviewed carefully. 
The other pull request just contains the fix for Thousand-Years Storm and adds hints to Sentinel Tower and Aetherflux Resovair #6645. The second pull request was the original idea behind this pull request here

**Pull request closed without merging**
