### PR TITLE
[PIP] Implement Piper Wright, Publick Reporter

### PR DESCRIPTION
**Pull request by Cguy7777**

### CODE REVIEW

**Review by xenohedron — APPROVED** [review]
btw, feel free to merge straightforward implementations that just use common classes

**Comment by Cguy7777** [comment]
Cool, I'll keep that in mind. :-)

**Comment by Cguy7777** [comment]
Tonight is not my night (see #12069). Is the way I merged this in going to cause problems?

**Comment by Cguy7777** [comment]
Okay, thank you. I'll be sure to check more closely in the future.

**Pull request merged**
