### PR TITLE
Added two Historical Standard deck validators

### PR DESCRIPTION
**Pull request by marthinwurer**
Two different rulesets: one from reddit.com/r/AllStandards, and one from http://thattournament.website/historic-tournament.php

### CODE REVIEW

**Comment by ZeldaZach** [comment]
I took a look at your code and it seems like you're missing some of the standards. Here's the code I used for the PHP deck checker I built, [found here](http://magic-league.com/zach/confirmDeck.php).

```
$historic_standard_array = array(	
		array("4ED", "DRK", "FEM"), // 1st Standard 
		array("4ED", "CHR", "FEM", "ICE", "HML", "ALL", "MIR"), // 2nd Standard
		array("4ED", "CHR", "ALL", "MIR", "VIS"), // 3rd Standard
		array("5ED", "ICE", "ALL", "HML", "MIR", "VIS", "WTH"), // 4th Standard
		array("5ED", "MIR", "VIS", "WTH", "TMP", "STH", "EXO"), // 5th Standard
		array("5ED", "TMP", "STH", "EXO", "USG", "ULG"), // 6th Standard
		array("6ED", "TMP", "STH", "EXO", "USG", "ULG", "UDS"), // 7th Standard
		array("6ED", "USG", "ULG", "UDS", "MMQ", "NMS", "PCY"), // 8th Standard
		array("6ED", "MMQ", "NMS", "PCY", "INV", "PLS"), // 9th Standard
		array("7ED", "MMQ", "NMS", "PCY", "INV", "PLS", "APC"), // 10th Standard
		array("7ED", "INV", "APC", "PLS", "ODY", "TOR", "JUD"), // 11th Standard
		array("7ED", "ODY", "TOR", "JUD", "ONS", "LGN", "SCG"), // 12th Standard
		array("8ED", "ODY", "TOR", "JUD", "ONS", "LGN", "SCG"), // 13th Standard
		array("8ED", "ONS", "LGN", "SCG", "MRD", "DST", "5DN"), // 14th Standard
		array("8ED", "MRD", "DST", "5DN", "CHK", "BOK", "SOK"), // 15th Standard
		array("9ED", "MRD", "DST", "5DN", "CHK", "BOK", "SOK"), // 16th Standard
		array("9ED", "CHK", "BOK", "SOK", "RAV", "GPT", "DIS", "CSP"), // 17th Standard
		array("9ED", "RAV", "GPT", "DIS", "CSP", "TSP", "TSB", "PLC", "FUT"), // 18th Standard
		array("10E", "RAV", "GPT", "DIS", "CSP", "TSP", "TSB", "PLC", "FUT"), // 19th Standard
		array("10E", "CSP", "TSP", "TSB", "PLC", "FUT", "LRW", "MOR", "SHM", "EVE"), // 20th Standard
		array("10E", "LRW", "MOR", "SHM", "EVE", "ALA", "CON", "ARB"), // 21st Standard
		array("M10", "LRW", "MOR", "SHM", "EVE", "ALA", "CON", "ARB"), // 22nd Standard
		array("M10", "ALA", "CON", "ARB", "ZEN", "WWK", "ROE", "M11"), // 23rd Standard
		array("M11", "ZEN", "WWK", "ROE", "SOM", "MBS", "NPH", "M12"), // 24th Standard
		array("M12", "SOM", "MBS", "NPH", "ISD", "DKA", "AVR", "M13"), // 25th Standard
		array("M13", "ISD", "DKA", "AVR", "RTR", "GTC", "DGM", "M14"), // 26th Standard
		array("M14", "RTR", "GTC", "DGM", "THS", "BNG", "JOU", "M15"), // 27th Standard
		array("M15", "THS", "BNG", "JOU", "KTK", "FRF", "DTK"), // 28th Standard
		array("DTK", "ORI", "BFZ") // 29th Standard
	);
```

**Comment by jgod** [comment]
Unless I'm missing something, aren't you missing the last 8 standards in both of these lists? Willing to pull it in no problem if it's correct.

**Comment by marthinwurer** [comment]
For the SuperStandard format, the first 10 standards are ignored. As for missing the last 8 standards, after Lorwyn/Alara, standard rotation became more consistent with the core sets, so you can determine which sets are in standard by the date that they were released.

**Comment by jgod** [comment]
Ah, I did miss something. Haven't tested but that makes sense and looks good. Thanks for your contribution!

**Pull request merged**
