### PR TITLE
Fix casting Transformed

### LINKED ISSUE #9686: [VOW] Disturb-related bugs with Dawnhart Geist and Brine Comber
Tested [[Dawnhart Geist]] effect with a couple of disturb auras and it didn't trigger. It triggers ok from normally cast enchantments.

[[Brine Comber]] and its aura side don't trigger from disturb auras.

### LINKED ISSUE #10271: Invasion of Tarkir's flipped dragon side counts as a non-creature spell
image

### PR DESCRIPTION
**Pull request by ssk97**
Combine casting Transformed into a shared SpellAbility- applies to Disturb, More than Meets the Eye, and part of Sieges' ability.
Apply transform effect before spell is cast, allowing cards to trigger off of the spells correctly.
Uses back side's characteristics when checking for cost addition/reduction effects.

Adds tests to confirm this behavior.

~This is a draft since I haven't yet done any manual testing and I may want to add some more documentation and/or more tests.~ Manual testing done, documentation seems good enough for now (let me know if there's somewhere I should add more).

For the Sieges I'm creating a temporary SpellAbility to cast it transformed with, testing seems to suggest that it isn't a problem. If you've got a better idea on how to handle that, let me know.

Fixes #9686
Fixes #10271

### CODE REVIEW

**Comment by Susucre** [comment]
Should fix #10271 ?

**Comment by xenohedron** [comment]
I won't claim to understand the intricacies of TDFCs, but this seems reasonable to me.

Is there any aspect of this that you consider a hack/workaround?

**Comment by ssk97** [comment]
> Is there any aspect of this that you consider a hack/workaround?

I don't like how for Battles I make a SpellTransformedAbility on the spot, but Java's garbage manager means that patterns like that aren't really a problem.

I feel like the applyEffects() call in the middle of casting is weird, but I highly doubt there's any better way without reworking TDFCs entirely.

**Comment by JayDi85** [comment]
> applyEffects() call in the middle of casting

Don't use it at all. Any `applyEffects()` usage smells bad and should be prohibited.

**Comment by JayDi85** [comment]
From #9686 by awjackson:
> The problem is that the continuous effect is not created until the very end of the spell casting (after super.activate() returns) and that is too late for various trigger to see that the spell is an Enchantment Aura and not a creature.

If that's true then it's a blood moon problem (#4202) and can't be fixed in current game engine without "look in the future" things or without migrate to MDFC engine (#10385).

**Comment by ssk97** [comment]
> Don't use it at all. Any `applyEffects()` usage smells bad and should be prohibited.

I could call `game.getState().processAction(game)` as noted in the comment if that'd be better?

The issue is that transform effects are implemented as basically a copy effect, and we need to apply that copy effect to the spell before the `SPELL_CAST` event is sent. By applying the effect in the middle of casting I'm able to do that.

**Comment by JayDi85** [comment]
> I could call game.getState().processAction(game) as noted in the applyEffects comment if that'd be better?

It's better, yes. But calls a processAction/applyEffects in the "activate" method is non standard thing and smells bad too (it must be called in apply/resolve by normal ways). Activate usage must be researched -- maybe some cards or abilities already uses same code style and it's safe -- I don't know yet.

> What I'm doing is creating the effect in the middle of spell casting and then applying it

There are a standard way to add and apply effect -- maybe it can help somehow:
shot_230812_074306

> since otherwise the effect would exist but it wouldn't be applied until after the casting is complete

Can you confirm what the original problem was and what is fixed in that PR?

1. TDFC (transforming double faced card) - normal cast:
  1.1. Has full characteristics: good/bad;
  1.2. Has full abilities/triggers: good/bad;
  1.3. Affected by own cost modification and effects: good/bad;
  1.4. Affected by another cost modification and effects: good/bad;

2. TDFC (transforming double faced card) - transformed cast like Disturb:
  2.1. Has full characteristics of the second side: good/bad;
  2.2. Has full abilities/triggers of the second side: good/bad;
  2.3. Affected by own cost modification and effects: good/bad;
  2.4. Affected by another cost modification and effects: good/bad;

**Comment by ssk97** [comment]
> There are a standard way to add and apply effect -- maybe it can help somehow:

Sure, I can use that pattern. It should be a lot more efficient too. Thanks!

> Can you confirm what the original problem was and what is fixed in that PR?

Transformed cast like Disturb used to:
1) Be affected by cost modification effects as if the front face were being cast
    -- Fixed via the change in `SpellAbilityCastMode.java`'s `getTypeModifiedCardObjectCopy()`
2) Cause triggered abilities to trigger as if the front face was cast
   -- Fixed via both adding and applying the effect in the middle of casting. (Disturb previously added it then but did not apply it. Battles previously added it after the cast)

Of the four tests I added:
`test_SpellAttributesOnStack2` Confirms correct behavior about MV which was not previously tested (but was correct)
`test_SpellAttributesTrigger` Checks for item 2 above for Disturb
`test_ConditionalCostModifications` Checks for item 1 above for Disturb
`testSpellCardTypeTrigger` Checks for item 2 above for Battles

**Comment by Susucre** [comment]
Maybe fix #10142 too? That one is maybe a more broad dfc bug.

**Comment by ssk97** [comment]
> Maybe fix #10142 too? That one is maybe a more broad dfc bug.

Didn't test it but I'm pretty sure that one isn't fixed.

From a very quick look (so quite possibly this is wrong), the issue there is that casting from the command zone uses a `CastCommanderAbility extends SpellAbility` and casting transformed uses a different class that extends `SpellAbility`. The `CastCommanderAbility` takes in the `SpellTransformedAbility` (or equivalent) but then copies it using the generic `SpellAbility` constructor.

**Comment by ssk97** [comment]
> edit: Might cause problems if there are other abilities that modify the spell though, I might need to add some test about that.

Just tested it, works correctly!

**Comment by xenohedron** [comment]
This is another one I'd like to get merged seeing as it fixes a couple bugs that affect entire mechanics. Maybe @theelk801 could take a look at it and determine if it is good to merge now? Not sure how this fits with the TDFC refactor #10385 but that might not be ready for a while.

**Review by xenohedron — APPROVED** [review]
This looks good to me now, if nobody raises an objection in the next couple days I'll plan to merge. It fixes the bugs according to the unit tests and I haven't heard of any progress on an alternative method of fixing them. Still plenty of work to be done on DFCs in future.

**Pull request merged**
