### PR TITLE
[M3C] Implement Planar Nexus and inroduce AllNonbasicLandTypes status

### PR DESCRIPTION
**Pull request by theelk801**
Gonna have to do a few things to make this work, luckily we have precedent from how changeling is implemented. Probably gonna do [[Nearby Planet]] too.

### CODE REVIEW

**Comment by theelk801** [comment]
yeah I caught a lot of them but I'll take another look to make sure I got them all

**Comment by theelk801** [comment]
need to add a few more tests but I think this is pretty close to ready

**Comment by Susucre** [comment]
Is there still work to do here?
I could add tests if that's only what's keeping it in a PR.

**Comment by theelk801** [comment]
yeah it just needs some more tests which I hadn't gotten around to adding, but feel free to if you'd like

**Review by Susucre — APPROVED** [review]

**Pull request merged**
