### PR TITLE
Implement Conspiracy

### PR DESCRIPTION
**Pull request by Dilnu**
Implemented conspiracy, based on Teferi, Story Circle, and Cast Through
Time

### CODE REVIEW

**Comment by emerald000** [comment]
Have you checked if the creature subtypes reset correctly for every zone if Conspiracy leaves the battlefield? There was issues with Painter's Servant in the past not resetting for non-permanents.

**Comment by Dilnu** [comment]
I managed to miss that issue. Do you know how it was solved for Painter's Servant?

**Comment by emerald000** [comment]
I don't remember exactly, but there was a creation of a game property that stores changes to non-permanents. So you put your changes there and make sure to read from there instead of the card itself.

**Comment by Dilnu** [comment]
So it looks like the handling for subtypes isn't implemented yet. I commented on the bug asking whether I should wait.

**Comment by Dilnu** [comment]
Alright, I fixed that handling. I've checked hand, stack and battlefield working correctly. The rest of the zones are implemented identically to hand so I'm pretty sure those will work too.

**Comment by drmDev** [comment]
We are unable to merge this pull request in at the moment. Please merge and push again so its up to date, then this can be merged into master.

**Comment by Dilnu** [comment]
I resynced, and I ran a quick test and everything seems to be working correctly with the merged code.

**Comment by drmDev** [comment]
Awesome! Thanks for your contributions!

**Pull request merged**
