### PR TITLE
Fixing Nahiri the Harbinger ultimate

### PR DESCRIPTION
**Pull request by baileybush**
a

### CODE REVIEW

**Comment by weirddan455** [comment]
I think you pushed the wrong thing.  These are old commits from 2017 that don't seem to be related to Nahiri.

**Comment by baileybush** [comment]
> I think you pushed the wrong thing. These are old commits from 2017 that don't seem to be related to Nahiri.

Yes, sorry this is my first time- I was trying to pull to edit. Found the issue in the source just did the wrong thing here

**Comment by weirddan455** [comment]
No worries.  You need to fork the repo if you haven't already, clone your fork down, commit your changes, then put in a PR.  There's some guides in the wiki here to help: https://github.com/magefree/mage/wiki/Setting-up-your-Development-Environment

**Comment by baileybush** [comment]
You're the best, thank you!

**Pull request closed without merging**
