### PR TITLE
Cards from Torment

### PR DESCRIPTION
**Pull request by LoneFox78**

### CODE REVIEW

**Comment by LevelX2** [comment]
For example DestroyTargetEffect has a parameter to allow multiTargetHandling.

**Comment by LoneFox78** [comment]
Better now?
What I don't understand here is why FixedTarget works differently than normal targets... Obviously changing it would be a lot of work, but is there a reason why it can't be done?

**Comment by LevelX2** [comment]
Don't know, it was implemented that way before my time in the project. 
At least it does not use an ability.modes.targets.target object and that's the reason your first solution won't work with it.
There are also some rare cases, if I remember right, were both is used, a fixed target and also a ability.modes.targets.target object.

**Comment by LevelX2** [comment]
Concerning your solution:
I guess it will work now in most cases.
A problem can only arise if you like to handle multiple targets for the effect and you need to set one as a FixedTarget. But I guess it's a more academic case also not handled in the other effects existing now.

**Pull request merged**
