### PR TITLE
Scryfall small images issue 11577

### PR DESCRIPTION
**Pull request by tiera3**
https://github.com/magefree/mage/issues/11577

### CODE REVIEW

**Comment by tiera3** [comment]
This is going to fail because an enum cannot use extends. Is there a simple fix or do I need to start over?

**Comment by Susucre** [comment]
> This is going to fail because an enum cannot use extends. Is there a simple fix or do I need to start over?

You could replace the single `instance` in ScryfallImageSource by two `SCRYFALL` and `SCRYFALL_SMALL`. Differentiate them with for instance a boolean `small` in the constructor, then use that to add the `?small` to the urls.

**Comment by tiera3** [comment]
Thanks. I will try again in two days.

**Comment by tiera3** [comment]
Accidentally committed to wrong branch - need to remove last commit. Will delete this message when done.

**Pull request closed without merging**
