### PR TITLE
[WIP] Consumable JSON game logs

### PR DESCRIPTION
**Pull request by hooptie45**
### WIP - Feedback / Guidance / Help Requested 

This exposes a JSON log of game interactions that can be analyzed.

As discussed in #4515

This is just a first pass, to get up to speed with how the messaging works. It'd like to trim down the messages much further so they don't include redundant information in each message. Also gson supports much more advances serialization options; such as using the @Expose annotation. We should probably use that, but I ran into some issues (I'm not a java developer, so still learning).

### TODO:
  These currently only exist on the client side; ideally we'd submit this logs back up to a central server after the games completion; thinking this could be simple via an S3 file drop, and a Lambda function to process and expose the logs; maybe via a kafka stream.

S3 Bucket with real play logs: https://s3.amazonaws.com/xmage-game-logs-dev/f6405fd7-dfba-4943-9510-fe75a6373f2b

Examples of log messages are below:

```
{
  "gameId": "2cede8c5-ff8e-4f8c-b9ac-66af53c0a254",
  "sessionId": "5c4o149-678483-je42ycva-1-je42ycw2-4",
  "type": "GAME_SELECT",
  "value": {
    "gameView": {
      "priorityTime": 3000,
      "players": [
        {
          "name": "computer",
          "life": 20,
          "counters": {}
        },
        {
          "name": "hooptie",
          "life": 20,
          "counters": {}
        }
      ],
      "hand": {
        "425d774f-ee0c-4a9b-8516-c98f886943f0": {
          "name": "Springleaf Drum",
          "power": "0",
          "toughness": "0",
          "loyalty": "",
          "manaCost": [
            "{1}"
          ],
          "convertedManaCost": 1,
          "type": 0,
          "paid": false,
          "id": "425d774f-ee0c-4a9b-8516-c98f886943f0"
        },
        "dd41bb4b-7fc3-4a3c-a69c-d18e281a1bff": {
          "name": "Blade of the Bloodchief",
          "power": "0",
          "toughness": "0",
          "loyalty": "",
          "manaCost": [
            "{1}"
          ],
          "convertedManaCost": 1,
          "type": 0,
          "paid": false,
          "id": "dd41bb4b-7fc3-4a3c-a69c-d18e281a1bff"
        },
        "06eb0a6c-1e70-4dc0-bd1c-93b6ea444806": {
          "name": "Ornithopter",
          "power": "0",
          "toughness": "2",
          "loyalty": "",
          "manaCost": [
            "{0}"
          ],
          "convertedManaCost": 0,
          "type": 0,
          "paid": false,
          "id": "06eb0a6c-1e70-4dc0-bd1c-93b6ea444806"
        },
        "a2f9cc13-e71a-4c9c-96aa-5424ea1a6b64": {
          "name": "Springleaf Drum",
          "power": "0",
          "toughness": "0",
          "loyalty": "",
          "manaCost": [
            "{1}"
          ],
          "convertedManaCost": 1,
          "type": 0,
          "paid": false,
          "id": "a2f9cc13-e71a-4c9c-96aa-5424ea1a6b64"
        },
        "91239f4f-9003-4c48-8ca1-4c318f892489": {
          "name": "Cranial Plating",
          "power": "0",
          "toughness": "0",
          "loyalty": "",
          "manaCost": [
            "{2}"
          ],
          "convertedManaCost": 2,
          "type": 0,
          "paid": false,
          "id": "91239f4f-9003-4c48-8ca1-4c318f892489"
        },
        "feb268d8-0535-4a9c-8915-83dd92a08c4c": {
          "name": "Arcbound Ravager",
          "power": "0",
          "toughness": "0",
          "loyalty": "",
          "manaCost": [
            "{2}"
          ],
          "convertedManaCost": 2,
          "type": 0,
          "paid": false,
          "id": "feb268d8-0535-4a9c-8915-83dd92a08c4c"
        }
      },
      "canPlayInHand": [
        "06eb0a6c-1e70-4dc0-bd1c-93b6ea444806"
      ],
      "stack": {},
      "combat": [],
      "phase": "PRECOMBAT_MAIN",
      "step": "PRECOMBAT_MAIN"
    },
    "message": "Play spells and abilities.",
    "options": {
      "queryType": "SELECT"
    }
  }
}
{
  "gameId": "2cede8c5-ff8e-4f8c-b9ac-66af53c0a254",
  "sessionId": "5c4o149-678483-je42ycva-1-je42ycw2-4",
  "type": "SEND_PLAYER_UUID",
  "value": "06eb0a6c-1e70-4dc0-bd1c-93b6ea444806"
}
{
  "gameId": "2cede8c5-ff8e-4f8c-b9ac-66af53c0a254",
  "sessionId": "5c4o149-678483-je42ycva-1-je42ycw2-4",
  "type": "GAME_CHOOSE_PILE",
  "value": {
    "choices": {
      "1ecf8671-be4c-4060-a76b-af614235a5b7": "Cast Ornithopter"
    }
  }
}
{
  "gameId": "2cede8c5-ff8e-4f8c-b9ac-66af53c0a254",
  "sessionId": "5c4o149-678483-je42ycva-1-je42ycw2-4",
  "type": "SEND_PLAYER_UUID",
  "value": "1ecf8671-be4c-4060-a76b-af614235a5b7"
}
```

### CODE REVIEW

**Comment by JayDi85** [comment]
`"Hand": ` must be array list, not object.

`"stack": {},` -- must be array too.

Each card have current abilities list (class/rule text) -- they are dynamic and must be in logs too.

**Comment by LevelX2** [comment]
There should be an option in preferences to activate/deactivate the creation of JSON game logs.
Maybe more options to control things like automatically uploading and level of JSON log details.

I guess it's important to focus on the usage of this created consumable game log to decide which information have to be in or out. This is for sure different from the decision which information has to be included in a server <=> client communiation on JSON base. As for the communication I would try to reduce already sent information as much as possible and to cache and handle the information on client side to reduce communiaction amount. The written out log could be very different to this.

> Each card have current abilities list (class/rule text) -- they are dynamic and must be in logs too. 

Abilities are currently included in the transfered rules text of the card. But I wonder if it's really useful to repeat the rules in thegame log every time you log a card. It would maybe make more sense for some things only to log changes (e.g. if the rule text of an obeject changes).
The rule text does anyway not control teh available option for an object. That's all handled server side and the client only requests the available actions for an UUID from the server.

> Also card's have owner and controller refs. 

Controller could also be determined by the battlefield area the object is in.

> Card types (creature, human) also dynamic and must show up in logs.

Very redundant but same is generally true for color, supertypes, tapped, transformed and more things .

What is "paid" on hand cards for?

Mana costs for the cards of xmage client are not changed currently.

**Comment by JayDi85** [comment]
> I would try to reduce already sent information as much as possible and to cache and handle the information on client side to reduce communiaction amount

Is big traffic the real problem? I remember someone post traffic stats from server on reddit and it was low.

> Abilities are currently included in the transfered rules text of the card.

Yes, it's very useful. For card rendering (not text, but other data too like #4488), for external AI, for replays.

> But I wonder if it's really useful to repeat the rules in thegame log every time you log a card. It would maybe make more sense for some things only to log changes

Not only rules/abilities, but other data too. Look at [recent example from reddit](https://www.reddit.com/r/XMage/comments/7wau94/demonic_pact/) with Demonic Pact. I try to render that hints, but can't -- used abilities stored by server side only, but it's a player side by fact (user know about it from game).


**Propose to use new logs for new replay system** -- this will help to debug and understand logs data and it's completing.

**Comment by hooptie45** [comment]
I started down this path with the use case of training an AI, so from that perspective this should include everything that would effect the perception of the game from a players perspective. Ie if it's visible in the current client, then it should be included. This should also have measures to ensure that nothing is ambiguous(so just returning card names is not viable, as there can be multiple with the same name; uuid is essential). 

There is alot of data in the GameView that is not relevant to the actual player, and more relevant to the client rendering; these things should be dropped. An example might be the paid attribute. 

I agree that there is a huge opportunity here to use this data for other things, which I'm very interested in pursuing. 

I'd like some help with building a GraphQL or rest based server  endpoint; which should implement all the possible player game actions, and respond with the resulting board state; the input and output of that system would be perfect for the replay system. 

I'm going to start development of a mobile game client for xmage, as I'd love to have something like "Words with friends", but for magic. I've got a friend who also wants to help out with that effort; we're both APP developers though, without much Java server programming experience. We're both very strong app developers though, and if given a Json payload of the GameView, we can quickly build a prototype. 

How can we coordinate this effort, and who is the best person to collaborate with; I'd like to get in touch with whomever that is, and maybe do a remote pairing session. 

GraphQL subscription would be perfect for this use case. Here is a good primer on that:
https://youtu.be/bn8qsi8jVew

Also, is there a slack channel for development?

**Comment by JayDi85** [comment]
@hooptie45 , main developer is @LevelX2 -- he is the best person for asking. Also there is a gitter chat for developers:
https://gitter.im/xmage-devs/Lobby

You can try to write specification requirements for your client/app/api like needed data, protocols, formats, client-server architecture, storages -- what's your app need from xmage.

**Comment by hooptie45** [comment]
I'd be happy to provide a draft request/response spec. I'd advocate for GraphQL; but a REST based Json endpoint could work also. If the REST method is preferred, I'll build a separate GraphQL server that will talk to it. 

For the request/response spec, I'll write it in the GraphQL model language since it's typed and easy to grok. I can also provide a basic test suite that'll hit that eventual endpoint. 

If I can get some help with the first couple operations, I can probably knock out the rest. At this point I don't really have enough Java server experience to even know where to start. 

I'll be joining the gitter chat, where maybe we can discuss this further.

**Comment by LevelX2** [comment]
I'm limited in available time. Also I wouldn't call me main developer.  :-)


I think a way to go could be to stay with the current way of using JBOSS and start adding a second type of user that is connecting/transfering data with a new technique like graphql.

So it would be possible to do it step by step. A first step could be to connect to the server and show the list of user and games. Going from this point expanding to more services.

I've seen a lot of tries in the past to do such a project. They all failed after some monthes because the initiator lost focus or didn't sole some problems.

So what's not clear for me, what services/protocols or else do we need to handle a complete new client without using JBOSS (what would be nice if we could create a client without).

Beside graphQl how can the server push something to the client?
Can you explain/or do you have an idea what would be the technical components/services we have to implement?

**Comment by hooptie45** [comment]
> I think a way to go could be to stay with the current way of using JBOSS and start adding a second type of user that is connecting/transfering data with a new technique like graphql.

I think I like that idea; would allow us to build this out with very little changes to the existing server initially. I'm picturing a proxy server, which will sit between the web client and the JBOSS server. It'll act as a server for the web API, and a client to the existing xmage server running jboss. It'll receive HTTP requests, then forward it to the actual xmage server via JBOSS. The proxy client will block until the server updates the `GameState`, and then return the `GameState` as JSON. 

```
                         +-----------------------------------+
                         |                                   |
                         |  Existing Server returning JBOSS  |
                         |                                   |
                         +-----------------+-----------------+
                                           |
                                           |
                                           |
                                           |
                                           |
+------------------------+                 |              +-------------------------------+
|                        |                 |              |                               |
|  Existing JAVA Client  +-----------------+--------------+  GraphQL or Rest Server       |
|                        |          JBOSS CONNECTION      |       (Xmage Client)          |
+------------------------+                                +---------------+---------------+
                                                                          ^
                                                                          |
                                                                          |
                                                                          |
                                                                          |
                                                                    HTTP CONNECTION
                                                                          |
                                                                          |
                                                                          |
                                                                          |
                                                                          |
                                                           +--------------+--------------+
                                                           |  Web or Mobile Based Client |
                                                           +-----------------------------+
```

> So what's not clear for me, what services/protocols or else do we need to handle a complete new client without using JBOSS (what would be nice if we could create a client without).

We could render the board using the data in the `GameState`. We'd interact with the board by using a similar API as the current client. For example, clicking on a permanent will submit the  permanent's `uuid` to the server; and it'll respond with the updated `GameState`. 

For the first iteration, a plain REST API is fine if that makes things more simple. A GraphQL server can be build on top of a REST api very easily; I can handle that work. 

Here is a draft of the datatypes and interactions:
```graphql
enum CardType {
  ARTIFACT
  CONSPIRACY
  CREATURE
  ENCHANTMENT
  INSTANT
  LAND
  PLANESWALKER
  SORCERY
  TRIBAL
}

type Player {
  name: String!
  id: ID! @isUnique
}

type Counter {
  count: Int!
  name: String!
}

type CardView {
  name: String!
  id: ID! @isUnique
  parentId: String
  setCode: String! # Scryfall Set Code (xln, m15, etc)
  setNumber: Int! # Scryfall collector/set number.
  power: Int
  toughness: Int
  manaCost: String
  cardTypes: [CardType!]!
  subTypes: [String!]!
  superTypes: [String!]!
  counters: [Counter!]! @relation(name: "Counter")
}

type PermanentView {
  tapped: Boolean
  damage: Int!
  copy: Boolean
  attachedTo: String
  morphed: Boolean
  manifested: Boolean
  original: CardView! @relation(name: "CardView")!
  summoningSickness: Boolean
}

 type PlayerView {
   id: ID!
   name: String!
   life: Int!
   wins: Int!
   winsNeeded: Int!
   exciles: [CardView!]!
   graveyard: [CardView!]!
   libraryCount: Int!
   topCard: CardView
   battlefield: [PermanentView!]!
   hasPriority: Boolean
   isActive: Boolean
 }

 type CombatView {
   defenderId: ID!
   attackers: [CardView!]!
   blockers: [CardView!]!
 }

 type GameView {
   players: [PlayerView!]!
   hand: [CardView]
   canPlayInHand: [ID] # UUID's of cards in hand which are playable right now
   activePlayerId: ID!
   turn: Int!
   stack: [CardView!]!
   combat: [CombatView!]!
 }

 type TableView {
   name: Str!
   id: ID!
   seats: [Player!]!
 }

# This will be passed in the HTTP headers on every request. The connection will
# not be persistent, so this will be used to maintain the session. 
# Client will make a JWT via the `login` action, and maintain it throughout the lifecycle. 
scalar JWT

# If we use a REST based API, these would be the GET requests; they're only for reading
type Query {
  game(id: ID!): GameView
  tables: [TableView]
  players: [Player]
}

# If we use a REST based API, these would be the POST requests; they're for changing server state. 
type Mutation {
  # This will get us an authenticated JWT token, which will be used
  # accross requests for authentication. It'll also establish a session
  # on the server.
  login(username: String!, password: String!): JWT

  # Clears the user's session and sets user's state to offline
  disconnect(): Boolean

  # Fired when you click on a permanent, sends permanent's
  # String to the server; server decides how that effects the board state
  sendPlayerUUID(value: ID!): GameView

  # Fired when you click DONE, or respond to question
  sendPlayerBoolean(value: Boolean!): GameView

  # Fired when you choose a value
  sendPlayerInteger(value: Int!): GameView

  # Fired when player chooses a String value
  sendPlayerString(value: String!): GameView

  # Used to make game tables
  createTable(name: String!, gameType: String!, numSeats: Int!): TableView

  # Remove a table you've created
  removeTable(name: String!, gameType: String!, numSeats: Int!): TableView

  # Join a table
  joinTable(tableId: String!): TableView

  # Leave a table
  leaveTable(tableId: String!): Boolean

  # Start a Game
  startGame(tableId: String!): GameView
}

schema {
  query: Query
  mutation: Mutation
}
```

**Comment by hooptie45** [comment]
So what would that look like in the current system? Would anyone like to take a crack at it? It'd be great for development if we could expose just enough of the API above so it'd be possible to interact with a running game in the old client, and see the results. I think we'd need the `login` and `JWT` support, and one of the mutations; like `sendPlayerUUID`. Then we'd be able to send requests via curl and actually see the board change in the existing JAVA client.

**Pull request merged**
