### PR TITLE
Attempted fix for Momir Free For All

### PR DESCRIPTION
**Pull request by pmbarrett314**
Work for #1955

### CODE REVIEW

**Comment by LevelX2** [comment]
What's the problem with the current implementation?

**Comment by pmbarrett314** [comment]
When I try to play Momir with 3 or more players, I can create the game, everyone can join, and then when I click start I am immediately taken back to the tables screen. If I run the server locally, the log shows an exception that is traced back to line 52 of MomirGame.java, saying that the class FreeForAll doesn't exist.

**Comment by LevelX2** [comment]
I can't reproduce that problem. I can play Momir mutilplayer games aginst the AI or with multiple human players without a problem.

**Comment by pmbarrett314** [comment]
I just reinstalled Xmage fresh and it's definitely still happening. I'm running on OSX if that makes a difference, but I can't imagine it would.

My procedure to reproduce:
1. Download a fresh xmage launcher to a separate folder
2. Run client and server and connect to local server
3. Create a new match, deck type Momir, game type Momir Free For All, at least 3 players
4. Add players with valid momir decks
5. Click start

The window with the start button disappears, but the game doesn't start. The server log shows java.lang.NoClassDefFoundError: mage/game/FreeForAll
...
Caused by: java.lang.ClassNotFoundException: mage.game.FreeForAll

I also just tried it on xmage.de with the same results, me and two other players joined, I clicked start, and the window disappeared but the game didn't start.

**Comment by Faxn** [comment]
I can confirm, I have the same problem on xmage.de or on a server from the launcher. Version:_1.4.28V1 (2018-03-18)_

`Exception in thread "CALL main-38" java.lang.NoClassDefFoundError: mage/game/FreeForAll`

I know when I submitted MomirFFA I only tested it off of starting the server through netbeans, so perhaps when it launches outside that the dependencies in the pom.xml aren't honored? Or perhaps I didn't set it up right in [pom.xml](https://github.com/pmbarrett314/mage/blob/dea874e27864e5d6fbc6a419e39de70826b7c795/Mage.Server.Plugins/Mage.Game.MomirGame/pom.xml#L25).

**Comment by LevelX2** [comment]
You're right, outside of netbeans it does currently bring up the mentioned error.

**Pull request merged**
