### PR TITLE
[MH2] Implemented Academy Manufactor

### PR DESCRIPTION
**Pull request by weirddan455**
Issue #7807 

I changed the token event code to support multiple types of tokens with a single event.  Without this change, I was running into infinite recursion on the replacement event.

### CODE REVIEW

**Comment by theelk801** [comment]
I'm too tired to look through this right now but you should probably add [[Chatterfang]] to this PR since it's also messing with token creation in a new way.

Right now these two cards are the only ones that modify token creation this way and there may be more in the set, plus there may be some rules clarifications for this kind of thing to keep in mind.

**Comment by weirddan455** [comment]
OK, I can do that.  That card should also work correctly with these changes.

**Comment by theelk801** [comment]
Alright now I've actually looked through it and it all seems good to me, but we should definitely leave this open until the full set is previewed in case they throw and more curveballs at us.

**Comment by theelk801** [comment]
Looks like we're good to go on this, thanks for making it work

**Pull request merged**
