### PR TITLE
Add rarity filters to deck editor

### PR DESCRIPTION
**Pull request by skeate**
Not sure if anybody besides me would find this useful, but I like it especially for building Pauper decks.

I got the icons from https://github.com/andrewgioia/Keyrune -- I can change them if you'd prefer something else (though I'm no artist)

### CODE REVIEW

**Comment by JayDi85** [comment]
I have a questions about [font license](https://github.com/andrewgioia/Keyrune#license)...

It's say: "All set symbol images are copyright Wizards of the Coast" -- is that a real open source resources? E.g. can it be distributed with xmage application (MIT give that) or it can be downloaded like current resources like images and symbols?

**Comment by skeate** [comment]
I'm not 100% sure on the licensing. The font itself is SIL Open Font License which is pretty permissive. But I know most symbols like that are downloaded separately, presumably for licensing issues (energy is a curious exception).

I could try to use the downloaded symbol (though that'll take me a bit more time to figure out) or just change the symbols to a colored box or something.

**Comment by LevelX2** [comment]
I guess we better avoid all possible image copyright problems. So best change it to other symbols.

**Comment by JayDi85** [comment]
I like simple symbols for it like: C, U, R, M, S (text is more user friendly than color).

Draw example (colored and uncolored icons):
shot_171231_151917

If that's fine then I can upload needed png images (any size: 16, 24, 32, 64 px).

P.S. Why it use non standard 20 px icons now?

**Comment by skeate** [comment]
That's a much better idea. I like the letters with colored background. As for the icon size -- I was just matching the other similar buttons in the deck editor. Not sure why they're 20x20

**Comment by JayDi85** [comment]
Added new icons in that commit 54e7c3cc99b82d28a51b351c5760c341bb487773

**Comment by skeate** [comment]
Updated to use those icons

**Pull request merged**
