### PR TITLE
[LCI] booster collation

### PR DESCRIPTION
**Pull request by tiera3**

### CODE REVIEW

**Comment by tiera3** [comment]
Would the actual runs (as per displayed sheets) be preferred for the dfc and land runs? My thoughts were that since only one card is selected at a time, it is better to reduce size and just have ratios of cards instead. But I can easily switch to the full shown runs if preferred.

**Comment by xenohedron** [comment]
If only one card from a run per pack, it is acceptable to simplify the actual runs to ratios.

**Comment by tiera3** [comment]
> If only one card from a run per pack, it is acceptable to simplify the actual runs to ratios. Just add a comment to clarify.

The following comments are already included. Are they not sufficient?
```
// Using 1:2 ratio for individual dfc uncommon:common - as per shown sheet - differs from text description
// Using 5:3 ratio for individual nonbasic:basic - matches both text desciption and shown sheet
```

**Comment by xenohedron** [comment]
Looks good to me.

<details>
<summary>Booster generation output</summary>

```
The Lost Caverns of Ixalan - boosters opened: 100000. Found cards: 1500000
LCI C Forest: 11478
LCI C Plains: 11267
LCI C Mountain: 11143
LCI C Swamp: 11126
LCI C Island: 11108
LCI C Petrify: 9567
LCI C Join the Dead: 9549
LCI C Mineshaft Spider: 9514
LCI C Poison Dart Frog: 9513
LCI C Rumbling Rockslide: 9510
LCI C Marauding Brinefang: 9510
LCI C Shipwreck Sentry: 9501
LCI C Adaptive Gemguard: 9495
LCI C Greedy Freebooter: 9490
LCI C Basking Capybara: 9483
LCI C Screaming Phantom: 9469
LCI C Compass Gnome: 9458
LCI C Malamet Scythe: 9457
LCI C Sage of Days: 9456
LCI C Tectonic Hazard: 9454
LCI C Cosmium Blast: 9449
LCI C Frilled Cave-Wurm: 9446
LCI C Cavern Stomper: 9446
LCI C Waterwind Scout: 9440
LCI C Didact Echo: 9439
LCI C Cogwork Wrestler: 9437
LCI C Sunfire Torch: 9436
LCI C Fanatical Offering: 9436
LCI C Out of Air: 9435
LCI C Hunter's Blowgun: 9435
LCI C Brackish Blunder: 9433
LCI C Thousand Moons Infantry: 9433
LCI C Ancestors' Aid: 9432
LCI C Pirate Hat: 9432
LCI C Disruptor Wanderglyph: 9432
LCI C Cartographer's Companion: 9431
LCI C Brazen Blademaster: 9430
LCI C Echo of Dusk: 9428
LCI C Deconstruction Hammer: 9418
LCI C Plundering Pirate: 9417
LCI C Attentive Sunscribe: 9412
LCI C Another Chance: 9411
LCI C Burning Sun Cavalry: 9410
LCI C Pathfinding Axejaw: 9409
LCI C Seismic Monstrosaur: 9404
LCI C Family Reunion: 9402
LCI C Glorifier of Suffering: 9399
LCI C Dead Weight: 9395
LCI C Skullcap Snail: 9393
LCI C Rampaging Spiketail: 9390
LCI C Armored Kincaller: 9388
LCI C Oltec Archaeologists: 9387
LCI C Ray of Ruin: 9386
LCI C River Herald Scout: 9383
LCI C Deep Goblin Skulltaker: 9383
LCI C Mephitic Draught: 9382
LCI C Relic's Roar: 9375
LCI C Etali's Favor: 9372
LCI C Child of the Volcano: 9371
LCI C Oaken Siren: 9371
LCI C Huatli's Final Strike: 9367
LCI C Song of Stupefaction: 9364
LCI C Envoy of Okinec Ahau: 9364
LCI C Malamet Veteran: 9363
LCI C In the Presence of Ages: 9358
LCI C Nurturing Bristleback: 9353
LCI C Orazca Puzzle-Door: 9348
LCI C Hotfoot Gnome: 9345
LCI C Daring Discovery: 9342
LCI C Tinker's Tote: 9336
LCI C Dinotomaton: 9336
LCI C Disturbed Slumber: 9333
LCI C Seeker of Sunlight: 9330
LCI C Primordial Gnawer: 9329
LCI C Goblin Tomb Raider: 9326
LCI C Acrobatic Leap: 9316
LCI C Buried Treasure: 9311
LCI C Miner's Guidewing: 9311
LCI C Quicksand Whirlpool: 9310
LCI C Oltec Cloud Guard: 9305
LCI C Ancestral Reminiscence: 9294
LCI C Ironpaw Aspirant: 9285
LCI C Unlucky Drop: 9281
LCI C Panicked Altisaur: 9281
LCI C Volatile Wanderglyph: 9277
LCI C Over the Edge: 9275
LCI C Walk with the Ancestors: 9269
LCI C Broodrage Mycoid: 9268
LCI C Vito's Inquisitor: 9264
LCI C Abrade: 9262
LCI C Waylaying Pirates: 9260
LCI C Fungal Fortitude: 9253
LCI C Sunshot Militia: 9248
LCI C Staggering Size: 9242
LCI C Deathcap Marionette: 9242
LCI C Runaway Boulder: 9237
LCI C Malamet Brawler: 9233
LCI C Acolyte of Aclazotz: 9232
LCI C Thousand Moons Crackshot: 9222
LCI C Soaring Sandwing: 9204
LCI C River Herald Guide: 9190
LCI C Oteclan Landmark: 9158
LCI C Inverted Iceberg: 9117
LCI C Kaslem's Stonetree: 9059
LCI C Idol of the Deep King: 9049
LCI C Tithing Blade: 9028
LCI C Hidden Cataract: 6380
LCI C Captivating Cave: 6324
LCI C Hidden Courtyard: 6274
LCI C Hidden Necropolis: 6257
LCI C Promising Vein: 6234
LCI C Hidden Nursery: 6212
LCI C Hidden Volcano: 6197
LCI U Spring-Loaded Sawblades: 4728
LCI U Lodestone Needle: 4674
LCI U Visage of Dread: 4563
LCI U Twists and Turns: 4561
LCI U Saheeli's Lattice: 4535
LCI U Grasping Shadows: 4525
LCI U Sunbird Standard: 4524
LCI U Waterlogged Hulk: 4523
LCI U Master's Guide-Mural: 4520
LCI U Dowsing Device: 4516
LCI U Jade Seedstones: 4485
LCI U Clay-Fired Bricks: 4435
LCI U Synapse Necromage: 3876
LCI U Malamet Battle Glyph: 3864
LCI U Dreadmaw's Ire: 3853
LCI U Calamitous Cave-In: 3841
LCI U Staunch Crewmate: 3838
LCI U Merfolk Cave-Diver: 3832
LCI U Triumphant Chomp: 3824
LCI U Self-Reflection: 3821
LCI U Captain Storm, Cosmium Raider: 3821
LCI U Goldfury Strider: 3818
LCI U Forgotten Monument: 3815
LCI U Volatile Fault: 3807
LCI U Sinuous Benthisaur: 3803
LCI U Malicious Eclipse: 3802
LCI U Hoverstone Pilgrim: 3799
LCI U Confounding Riddle: 3798
LCI U Uchbenbak, the Great Mistake: 3797
LCI U Caparocti Sunborn: 3796
LCI U Zoyowa Lava-Tongue: 3795
LCI U Bartolome del Presidio: 3794
LCI U Bat Colony: 3792
LCI U Spelunking: 3790
LCI U Akawalli, the Seething Tower: 3788
LCI U Digsite Conservator: 3783
LCI U Colossadactyl: 3782
LCI U Enterprising Scallywag: 3780
LCI U Sorcerous Spyglass: 3779
LCI U Itzquinth, Firstborn of Gishath: 3777
LCI U Ruin-Lurker Bat: 3776
LCI U Ixalli's Lorekeeper: 3770
LCI U Bloodthorn Flail: 3769
LCI U Hermitic Nautilus: 3769
LCI U Nicanzil, Current Conductor: 3767
LCI U Vanguard of the Rose: 3766
LCI U Deep-Cavern Bat: 3763
LCI U Contested Game Ball: 3763
LCI U Might of the Ancestors: 3763
LCI U Spyglass Siren: 3762
LCI U Pit of Offerings: 3762
LCI U Coati Scavenger: 3761
LCI U Dusk Rose Reliquary: 3758
LCI U Belligerent Yearling: 3758
LCI U Council of Echoes: 3757
LCI U Tendril of the Mycotyrant: 3754
LCI U Curator of Sun's Creation: 3748
LCI U Cenote Scout: 3747
LCI U Swashbuckler's Whip: 3741
LCI U Gargantuan Leech: 3739
LCI U Kutzil, Malamet Exemplar: 3739
LCI U Chart a Course: 3738
LCI U Bitter Triumph: 3736
LCI U Careening Mine Cart: 3735
LCI U Eaten by Piranhas: 3734
LCI U Geological Appraiser: 3730
LCI U Abyssal Gorestalker: 3729
LCI U Helping Hand: 3712
LCI U Hurl into History: 3710
LCI U Zoetic Glyph: 3709
LCI U Kinjalli's Dawnrunner: 3706
LCI U Soulcoil Viper: 3706
LCI U Scampering Surveyor: 3704
LCI U Scytheclaw Raptor: 3701
LCI U Canonized in Blood: 3700
LCI U Dauntless Dismantler: 3699
LCI U Earthshaker Dreadmaw: 3698
LCI U Mischievous Pup: 3696
LCI U Thrashing Brontodon: 3695
LCI U Explorer's Cache: 3694
LCI U Glowcap Lantern: 3693
LCI U Defossilize: 3681
LCI U Stinging Cave Crawler: 3681
LCI U Guardian of the Great Door: 3678
LCI U Rampaging Ceratops: 3673
LCI U Chupacabra Echo: 3668
LCI U Zoyowa's Justice: 3666
LCI U Market Gnome: 3644
LCI U Cavernous Maw: 3638
LCI U Glimpse the Core: 3631
LCI U Diamond Pick-Axe: 3615
LCI U Malamet War Scribe: 3603
LCI R Growing Rites of Itlimoc: 1410
LCI R Stalactite Stalker: 1396
LCI R Roaming Throne: 1387
LCI R Hit the Mother Lode: 1384
LCI R Dire Flail: 1384
LCI R Abuelo, Ancestral Echo: 1383
LCI R Bringer of the Last Gift: 1381
LCI R Sunken Citadel: 1380
LCI R Abuelo's Awakening: 1379
LCI R Palani's Hatcher: 1378
LCI R Poetic Ingenuity: 1375
LCI R Tishana's Tidebinder: 1375
LCI R Restless Vents: 1371
LCI R Warden of the Inner Sky: 1367
LCI R Preacher of the Schism: 1367
LCI R Starving Revenant: 1361
LCI R Braided Net: 1359
LCI R Matzalantli, the Great Door: 1357
LCI R Kellan, Daring Traveler: 1357
LCI R Restless Reef: 1355
LCI R Thousand Moons Smithy: 1354
LCI R Malcolm, Alluring Scoundrel: 1353
LCI R Squirming Emergence: 1349
LCI R Hulking Raptor: 1345
LCI R Subterranean Schooner: 1344
LCI R Restless Prairie: 1344
LCI R Get Lost: 1342
LCI R Cosmium Confluence: 1340
LCI R The Belligerent: 1338
LCI R Corpses of the Lost: 1337
LCI R Wail of the Forgotten: 1336
LCI R Sanguine Evangelist: 1335
LCI R Molten Collapse: 1332
LCI R Tarrian's Soulcleaver: 1332
LCI R Breeches, Eager Pillager: 1331
LCI R Brass's Tunnel-Grinder: 1331
LCI R Magmatic Galleon: 1328
LCI R Anim Pakal, Thousandth Moon: 1327
LCI R Inti, Seneschal of the Sun: 1327
LCI R Bedrock Tortoise: 1326
LCI R Intrepid Paleontologist: 1325
LCI R Jadelight Spelunker: 1325
LCI R Kutzil's Flanker: 1321
LCI R Treasure Map: 1316
LCI R Echoing Deeps: 1316
LCI R Kitesail Larcenist: 1315
LCI R Throne of the Grim Captain: 1315
LCI R Trumpeting Carnosaur: 1314
LCI R Restless Anchorage: 1313
LCI R Deeproot Pilgrimage: 1313
LCI R Queen's Bay Paladin: 1313
LCI R Unstable Glyphbridge: 1311
LCI R Amalia Benavides Aguirre: 1301
LCI R Restless Ridgeline: 1301
LCI R Akal Pakal, First Among Equals: 1301
LCI R Fabrication Foundry: 1299
LCI R Souls of the Lost: 1294
LCI R Tarrian's Journal: 1294
LCI R Pugnacious Hammerskull: 1292
LCI R Terror Tide: 1289
LCI R Sentinel of the Nameless City: 1286
LCI R The Everflowing Well: 1283
LCI R Threefold Thunderhulk: 1270
LCI R Deepfathom Echo: 1255
LCI M The Ancient One: 711
LCI M Ojer Pakpatiq, Deepest Epoch: 709
LCI M Ojer Taq, Deepest Foundation: 682
LCI M Gishath, Sun's Avatar: 681
LCI M Sovereign Okinec Ahau: 679
LCI M Bloodletter of Aclazotz: 677
LCI M Ojer Axonil, Deepest Might: 666
LCI M Bonehoard Dracosaur: 664
LCI M Ghalta, Stampede Tyrant: 662
LCI M Chimil, the Inner Sun: 661
LCI M Vito, Fanatic of Aclazotz: 660
LCI M Saheeli, the Sun's Brilliance: 658
LCI M The Skullspore Nexus: 657
LCI M The Millennium Calendar: 652
LCI M Ojer Kaslem, Deepest Growth: 651
LCI M Cavern of Souls: 650
LCI M The Enigma Jewel: 638
LCI M Aclazotz, Deepest Betrayal: 633
LCI M Quintorius Kand: 629
LCI M Huatli, Poet of Unity: 627
LCI M The Mycotyrant: 626
LCI M Resplendent Angel: 608
```

</details>

**Pull request closed without merging**
