### PR TITLE
Implement [CMM] Hatchery Sliver; fix Replicate ability

### LINKED ISSUE #10702: Rework Replicate ability to handle multiple instances independently
Found while implementing Hatchery Sliver (#10694).

> 702.56b. If a [spell](https://yawgatog.com/resources/magic-rules/#spell) has multiple instances of [replicate](https://yawgatog.com/resources/magic-rules/#replicate), each is paid separately and [triggers](https://yawgatog.com/resources/magic-rules/#trigger) based on the payments made for it, not any other instance of [replicate](https://yawgatog.com/resources/magic-rules/#replicate).

As currently implemented in XMage, this rule isn't being followed. When additional cost is paid for one instance, the other instances also notice it and produce additional copies.

I'm not sure where to start with trying to fix this, hopefully someone else has an idea.

### PR DESCRIPTION
**Pull request by xenohedron**
Also fixes Replicate ability to comply with the ruling:
> 702.56b. If a [spell](https://yawgatog.com/resources/magic-rules/#spell) has multiple instances of [replicate](https://yawgatog.com/resources/magic-rules/#replicate), each is paid separately and [triggers](https://yawgatog.com/resources/magic-rules/#trigger) based on the payments made for it, not any other instance of [replicate](https://yawgatog.com/resources/magic-rules/#replicate).

closes #10702

### CODE REVIEW

**Comment by Susucre** [comment]
Oh did not think of multi replicate ruling. I'll close my attempt at implementing it.

**Comment by xenohedron** [comment]
@Susucre @ssk97 I tried the suggested idea of using the UUID to link it and it seems to work well. Do you see any issues? The triggers appear identical even though they might not be, but that seems minor/obscure enough to leave as is.

**Comment by ssk97** [comment]
Here's the potential issues I noticed, didn't check to see if it actually works correctly or not:
1) If the Hatchery Sliver is killed between casting the spell and the trigger resolving, which would remove the Replicate ability but should still copy the spell
2) If making a copy that's then cast with Replicate works correctly.
3) Make sure it works correctly with cards normally in decks, my Squad implementation works perfectly when cards are created in hand but seems to sometimes fail with decks using it (possibly also something to do with rollbacks? Didn't investigate since the Cost Tags changes would resolve that too)

**Comment by xenohedron** [comment]
1. Works fine, added a test case
2. Doesn't work yet as `EachSpellYouCastHasReplicateEffect` checks `stackObject.isCopy()`, that's a rework outside the scope of this card implementation
3. Haven't explicitly tested; I don't see why this card would be unusually susceptible but certainly rollbacks cause weirdness sometimes.

**Comment by ssk97** [comment]
> 3\. Haven't explicitly tested; I don't see why this card would be unusually susceptible but certainly rollbacks cause weirdness sometimes.

The potential problem is that Replicate now needs a consistent ID. Making a copy of a card with replicate would copy all the abilities, and the subability's ID reference isn't updated. This is very closely related to the current Squad not working bug.

Right now I guess it'd be fine since you'd get multiple Replicate Triggered subabilities, one with a reference to the previous ability and thus would never trigger whereas the other would be fine. Once the subability bug is fixed, that might be a problem.

**Comment by xenohedron** [comment]
Shouldn't the UUID of the ability be consistent when copying the game state?

**Comment by ssk97** [comment]
Sorry, I meant to specify to check the older cards with Replicate on the card directly.

**Comment by ssk97** [comment]
To be more precise: you assign the id in the constructor, but if `newId()` or `newOriginalId()` is called then the ID of the subability isn't updated, and those functions are called in several places.

**Comment by xenohedron** [comment]
Yeah, I see what you're saying about `newId()`. I'm not sure how to deal with that, but also don't have a clear example of it mattering.

I did test existing replicate cards in a deck and worked as expected.

**Comment by ssk97** [comment]
Looks like you've tested it as much as is reasonable then.

I think we should at some point look at properly implementing linked abilities but this should be fine for now.

**Pull request merged**
