### PR TITLE
[WOE] Implement Faerie Slumber Party

### PR DESCRIPTION
**Pull request by Susucre**

### CODE REVIEW

**Review by xenohedron — COMMENTED** [review]
Looks good, though curious about the edge case of replacement effects preventing the creatures from being returned to hand. [Scryfall search for example](https://scryfall.com/search?q=o%3A%22would+leave+the+battlefield%2C+%22+o%3A%22instead+of+putting+it+anywhere+else%22&unique=cards&as=grid&order=name)

**Comment by Susucre** [comment]
Yeah I was not sure either. Hopefully they will think about the command rule and provide 1 ruling if you look for owner of the returned permanents or of cards actually returned in hand.

**Comment by xenohedron** [comment]
I don't see a ruling in the release notes. @theelk801 what do you think?

**Comment by theelk801** [comment]
I'm not sure but I just asked the rules manager and head editor on twitter, also it's always worth asking in the [judge chat](https://chat.magicjudges.org/mtgrules/)

**Comment by Susucre** [comment]
Alright, a less convoluted situation is commanders going back to command zone, no need for instant speed an unearth creature.

**Comment by Susucre** [comment]
And the code is counting from the permanents not from the result of cards returning, so we're good.

**Review by theelk801 — CHANGES_REQUESTED** [review]

**Pull request merged**
