### PR TITLE
Feature/Add Set Selection filtering

### PR DESCRIPTION
**Pull request by salco**
Someone asked me to create a button to filter the Set in the Deck Editor.
So I want to send this request.

### CODE REVIEW

**Comment by chrvanorle** [comment]
The build issue is fixed in https://github.com/magefree/mage/pull/4709. You can restart the Travis checks by closing and reopening your pull request!

**Comment by JayDi85** [comment]
My marks about PR:
shot_180403_192026

1, 2 and 3 can be fixes, others for info (it's more complicated).

Also your code needs to refactor. First of all -- rename files to real names like "PickListDialog.java" or even best: "PickSetListDialog". XMage have another set list select dialog in match setup -- it's can be replaced to new one in the future.

**Comment by salco** [comment]
I think I've manage to resolve all point asked. Tell me if everything is ok.

**Comment by salco** [comment]
Never-mind I think the File I change was used by other file. I will need to check at it.

**Comment by LevelX2** [comment]
COMPILATION ERROR : 
-------------------------------------------------------------
mage/client/deck/generator/DeckGeneratorDialog.java:[138,64] incompatible types: javax.swing.JComboBox cannot be converted to mage.client.dialog.CheckBoxList
mage/client/dialog/NewTournamentDialog.java:[935,72] incompatible types: javax.swing.JComboBox cannot be converted to mage.client.dialog.CheckBoxList
mage/client/deckeditor/collection/viewer/CollectionViewerPanel.java:[121,64] incompatible types: javax.swing.JComboBox cannot be converted to mage.client.dialog.CheckBoxList
mage/client/dialog/AddLandDialog.java:[469,56] incompatible types: javax.swing.JComboBox cannot be converted to mage.client.dialog.CheckBoxList
4 errors

**Comment by JayDi85** [comment]
Code is not compatible with choices dialogs and comboboxes all around xmage. Need to revert that code. First PR with different PickChoiceDialog file for checkboxes was correct.

**Comment by salco** [comment]
I dont understand did you merge the thing? It was not completed...

**Comment by JayDi85** [comment]
@salco it was mistaken merged and later reverted. When it's will be done then you can create new pull request.

**Pull request merged**
