### PR TITLE
[M3C] Implement Ulalek, Fused Atrocity and new colorless hybrid mana

### PR DESCRIPTION
**Pull request by theelk801**
This isn't done, hybrid colorless mana is turning out to be pretty annoying to do

### CODE REVIEW

**Comment by xenohedron** [comment]
Why use `null` as special case rather than an explicit colorless case?

**Comment by theelk801** [comment]
I'm still figuring that part out, I'm not sure if having `ColoredManaSymbol.C` for colorless would make sense since colorless isn't colored

**Comment by JayDi85** [comment]
[[Ulalek, Fused Atrocity]]

**Comment by alexander-novo** [comment]
I think that there is some room to slightly redesign `HybridManaCost` - right now it is specifically designed to only support two colored costs. Other hybrid symbols, such as the ones found on [[Beseech the Queen]] and [[Reaper King]] use a different class. I think that's slightly inflexible, though, and I think that rather than having a different class for each special case of hybrid mana, it makes sense to replace the `ColoredManaSymbol` instances in `HybridManaCost` with something like `ManaSymbol` (and enforce that the individual symbols cannot be hybrid themselves). This would be more future-proof.

**Comment by alexander-novo** [comment]
Actually the more and more I'm looking at hybrid mana code, the more I realise that while a rework of hybrid mana would be a good thing - it would probably be outside the scope of this particular card. I guess `ManaCost` treats colorless mana as a separate thing from the rest of the colors, so it would be better to have a new hybrid mana cost class to support it.

**Comment by alexander-novo** [comment]
Also another issue is that Devoid doesn't seem to work with commanders:

image

**Comment by alexander-novo** [comment]
Actually I think that might be the same problem as #9852

**Comment by alexander-novo** [comment]
Something to consider: I'm not sure if this is this first example of a card which copies multiple stack items at the same time, but the UX for it is kind of bad - there isn't a way to choose what order they go onto the stack. I don't think it's a blocker, but it will probably need to get fixed eventually.

**Comment by alexander-novo** [comment]
@JayDi85 Careful with that merge - there was a conflict

**Pull request merged**
