### PR TITLE
Refactor: Delete commented out code blocks in GameImpl.java

### PR DESCRIPTION
**Pull request by DeepCrimson**
As titled, deleting commented out blocks of code in GameImpl.java.

### CODE REVIEW

**Comment by JayDi85** [comment]
Do not delete commented code in copy section. It's important part (why some
fields doesn't copy).

**Comment by aecallahan** [comment]
> Do not delete commented code in copy section. It's important part (why some fields doesn't copy).

@JayDi85 what is the copy section?

**Comment by DeepCrimson** [comment]
> Do not delete commented code in copy section. It's important part (why some fields doesn't copy).

@JayDi85 what is the copy section?

**Comment by JayDi85** [comment]
Xmage uses copy constructors for all game objects (see constructor with
same class param) . So that's constructor must copy all class fields in
99%. Only temporary data can be miss from copy. IntelliJ have a special
check for miss fields in copy constructors.

Miss fields in the copy is a popular and weird bug (card didn't work after
some time or rollback).

**Comment by DeepCrimson** [comment]
> Xmage uses copy constructors for all game objects (see constructor with same class param) . So that's constructor must copy all class fields in 99%. Only temporary data can be miss from copy. IntelliJ have a special check for miss fields in copy constructors. Miss fields in the copy is a popular and weird bug (card didn't work after some time or rollback).

@JayDi85 thanks for the explanation. I updated this PR with that in mind, let me know if this is still deleting any copy code.

**Pull request merged**
