### PR TITLE
Implement 7 cards

### PR DESCRIPTION
**Pull request by FenrisulfrX**
Implemented cards need to recreate the Ajani vs. Nicol Bolas decks.
Cards Implemented:
* Agonizing Demise
* Fleetfoot Panther
* Morgue Toad
* Ogre Savant
* Pain // Suffering
* Spite // Malice
* Steamcore Weird

### CODE REVIEW

**Comment by FenrisulfrX** [comment]
I based those cards off [TinStreetHooligan](https://github.com/magefree/mage/blob/master/Mage.Sets/src/mage/sets/guildpact/TinStreetHooligan.java) so I'm guessing that's also wrong?

Should I remove those cards? I have no idea how to do that nor did I find something to base these on. I tried something like 
```java        
        TriggeredAbility ability = new EntersBattlefieldTriggeredAbility(new ReturnToHandTargetEffect());
        ability.addTarget(new TargetCreaturePermanent());
        this.addAbility(new ConditionalTriggeredAbility(ability, new ManaWasSpentCondition(ColoredManaSymbol.U),
                "if {U} was spent to cast Ogre Savant, return target creature to its owner's hand."));
```

but spending {U} doesn't trigger the ability.

**Comment by FenrisulfrX** [comment]
After thinking about it for a bit I have this: 
```java
Ability ability = new ConditionalTriggeredAbility(new EntersBattlefieldTriggeredAbility(new ReturnToHandTargetEffect()),
        new ManaWasSpentCondition(ColoredManaSymbol.U),
        "if {U} was spent to cast Ogre Savant, return target creature to its owner's hand.");
ability.addTarget(new TargetCreaturePermanent());
this.addAbility(ability, new ManaSpentToCastWatcher());
```
which almost works, the condition triggers fine, but the effect never takes place, thoughts?

**Comment by LevelX2** [comment]
> which almost works, the condition triggers fine, but the effect never takes place, thoughts?

Problem is that the used watcher resets the information after each call of the getAndResetLastPayment method and the Triggered ability condition is called multiple times during ability resolution.
I've chnaged the reset handling of ManaSpentToCastWatcher. Pull the change and try if it works after that change.

**Comment by FenrisulfrX** [comment]
@LevelX2 After your changes the cards work as intended, thanks. I hope I adressed all coments.

**Comment by LevelX2** [comment]
Yes, the cards looked good otherwise.

**Pull request merged**
