### PR TITLE
[IKO] Implement Companion and 2 companions

### PR DESCRIPTION
**Pull request by emerald000**
Keruga, the Macrosage and Umori, the Collector

### CODE REVIEW

**Comment by theelk801** [comment]
This looks great, thank you so much for making it work.

**Comment by JayDi85** [comment]
@emerald000 is freeze problem was fixed?

**Comment by JayDi85** [comment]
Good. Please, can you test it with ingame restart from [Karn Liberated](https://scryfall.com/card/uma/5/karn-liberated) ability too.

**Comment by emerald000** [comment]
Also seems to work correctly. Companions that were cast get shuffled into the deck, and you can choose a new companion upon the start of the new game.

**Comment by theelk801** [comment]
I just realized, does this check for companions in regular constructed and limited?

**Comment by JayDi85** [comment]
Also it must work with oathbreakers and commanders with partner.

**Comment by emerald000** [comment]
For constructed, it's a normal card in your sideboard, so there is no deckbuilding difference.

For Oathbreaker, they announced the format would not support Companions: https://oathbreakermtg.org/ikoria-in-a-world-of-monsters-jeskais-the-limit-companion-rulings/

**Comment by JayDi85** [comment]
So oathbreaker decks works fine or broken with new code?

**Comment by emerald000** [comment]
Works fine. I went through all the formats to make sure everything was fine.

**Pull request merged**
