### PR TITLE
Implement Hidden Retreat. 

### PR DESCRIPTION
**Pull request by ingmargoudt**
The code is based of the card 'Penance'. I have no idea what the collector's number is..

### CODE REVIEW

**Comment by rystan** [comment]
Looks like the Travis tests are failing because of other issues   Nely cards rotating out of standard in the testStandardValid tests.  AER & KLD have been removed from standard.

**Comment by LevelX2** [comment]
You need to implement a target ("target instant or sorcery") that is selected during the announcement of the spell.

That is different to 'Penance'.

**Comment by ingmargoudt** [comment]
I will implement the Target as suggested

**Comment by jeffwadsworth** [comment]
Target target = new TargetSpell(StaticFilters.FILTER_SPELL_INSTANT_OR_SORCERY);
Ability ability = new Simple.....
ability.addTarget(target);

**Comment by jeffwadsworth** [comment]
Implemented this to finish off the set.

**Pull request closed without merging**
