### PR TITLE
Beamtown Bullies now properly targets opponent

### PR DESCRIPTION
**Pull request by alexander-novo**
Fixes magefree/mage#9975

### CODE REVIEW

**Comment by Grath** [comment]
This works, but that's not how filters are configured in XMage. Please revert FilterPlayer, then set it up similar to the nonlegendary creature card filter:

`private static final FilterPlayer playerFilter = new FilterOpponent();`

then in the `static` block, add `playerFilter.add(ActivePlayerPredicate.instance);`

**Comment by Grath** [comment]
Well, I suppose it's fine to leave the changes to FilterPlayer, then, but should still make sure the filter initialization is consistent with how every other filter setup I've seen in XMage is done (with the added predicates in the static{} block, how the other filter is already set up in this file)

**Comment by alexander-novo** [comment]
Already done. For some reason, Github isn't updating the PR even though my branch is updated.

**Comment by Grath** [comment]
I think Github's having an issue, because I'm reviewing this PR while waiting for my PR at my day job to update with the code I pushed to that branch. I'll merge it once Github remembers how to function properly and pulls in the update.

**Comment by alexander-novo** [comment]
Ayyy it caught up

**Pull request merged**
