### PR TITLE
[READY] Add GitHub Actions bot that fetches cards in comments (through one little GitHub Action)

### PR DESCRIPTION
**Pull request by ldeluigi**
### WTF?
This GitHub Action workflow enables and runs an action which I developed: https://github.com/marketplace/actions/mtg-fetch-action.
Generally speaking this action is extremely useless. **But**, inspired by the issues that normally are raised here and the Reddit MtgFetcher bot I thought it would be great to have it on GitHub too.

For example, you will be able to comment an issue with `[[Island]]` to make the bot fetch an Island and paste the links (well formatted) as answer in the issue thread.

### Improvement
Feel free to ask questions, suggest features and complain about it in the future. I'll stay as maintainer of it.

### Why GitHub Actions
I see that XMage currently uses Travis CI for CI/CD, but Travis recently changed its policies and now its substantially a must-pay platform. Travis can't react to events outside the push/pr scope so there is no more convenient way to implement this bot. GitHub refuels your monthly CPU linux minutes so that u/magefree won't run out (this is an Open Source project so cpu time could even be infinite if I remember correctly).

------------------
If you like my idea: _you are welcome, my pleasure to help._

### CODE REVIEW

**Comment by JayDi85** [comment]
It will be useful to have default settings, e.g. force all `[[xxx]]` to use same source and settings. I don't want link to "ugly" gatherer site, so what I expect to see after `[[card]]`:
* card name with links to scryfall (the main link) and gatherer;
* card's rules as quoted text;

P.S.

> now its substantially a must-pay platform

Travis have a special open source plan with renewable credits. So it's possible to run travis after migration to new website (from org to com). XMage needs 100 oss credits per build or 30-60k pre most active prerelease month. I don't see problems with it. From docs:
> On occassion, an allotment of OSS Only credits may be granted by Travis CI. These credits may be used only for builds over public repositories and are meant for open source support. The OSS credits may be assigned as one time pool or renewable pool, subject to case by case assesment of Travis CI staff.

**Comment by ldeluigi** [comment]
Quick reference: https://github.com/marketplace/actions/mtg-fetch-action#quick-reference
Websites linked: gatherer, scryfall, edhrec

**Comment by ldeluigi** [comment]
About Travis: unless you agree with the staff for renewable credits your pipeline is doomed to run out of them. This is why most of their "free" customers moved away from the platform (myself included)

**Comment by JayDi85** [comment]
If it's a spam depends then one link possible -- scryfall. With text, not image. Copy-pastable text is important. Look at scryfall bot example from discord:

shot_201227_174221

**Comment by ldeluigi** [comment]
> {1}{G}
> Legendary Creature — Bear
> 2/2
> Whenever another Bear enters the battlefield under your control, choose one —
> • Put two +1/+1 counters on target Bear.
> • Target Bear you control fights target creature you don’t control.

I'll see what I can do for this. In the meantime try the bot as it is now to have a little more experience on its usability

**Comment by ldeluigi** [comment]
Here by merging or in the test playground on the bot repository

**Comment by ldeluigi** [comment]
@JayDi85 I implemented the text preview. 🚀

**Comment by JayDi85** [comment]
Don't forget about loyalty instead p/t on planeswalkers.

**Comment by ldeluigi** [comment]
🙄

**Comment by ldeluigi** [comment]
Done 🙈 @JayDi85

**Comment by ldeluigi** [comment]
It's been a month... any news? @JayDi85

**Comment by JayDi85** [comment]
@ldeluigi warning messages in bot logs -- is that ok?
https://github.com/magefree/mage/pull/7528/checks?check_run_id=1877323700

> Warning: Event name is not in [issues, issue_comment, pull_request]!

**Comment by ldeluigi** [comment]
I'm working on supporting pull reviews and reviews comment now

**Comment by ldeluigi** [comment]
Done.

**Comment by JayDi85** [comment]
@ldeluigi another warning message in fetch bot:
https://github.com/magefree/mage/pull/7784/checks

Use case:
- new github's feature for PRs: PR from new user can't be run, [maintainer must approve it first](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks);
- I approved it (#7784) and wait to complete all checks;
- Then added review with comment and merged it after 1-2 minutes;
- Fetch bot catch "action required" warning message:
shot_210429_095717

Also got that email:
shot_210429_094723

**Comment by ldeluigi** [comment]
Unfortunately, we can't disable this behaviour, as it's described here:
image
Source: https://github.blog/2021-04-22-github-actions-update-helping-maintainers-combat-bad-actors/

At the moment, contributors with write access **must** approve workflow execution (including our fetch bot) every time a new contributor submits their first PR to the project. When GitHub will provide an opt-out option for whis behaviour we will take action.

Thanks for reporting.

**Comment by JayDi85** [comment]
@ldeluigi another issue in commit's comments -- fetch bot doesn't work here 8d0efaabc96aed637f3d9905f1adb9bcc734c86b

**Comment by ldeluigi** [comment]
Will be fixed, thanks

**Comment by ldeluigi** [comment]
> @ldeluigi another issue in commit's comments -- fetch bot doesn't work here [8d0efaa](https://github.com/magefree/mage/commit/8d0efaabc96aed637f3d9905f1adb9bcc734c86b)

Unfortunatley this can't be done due to security reasons:
https://github.community/t/can-we-have-on-commit-comment-as-a-trigger/16736/2

**Comment by JayDi85** [comment]
@ldeluigi can you look at #9207 for another fetch bot issue in PR?

**Pull request merged**
