### PR TITLE
Fixed maddening hex

### PR DESCRIPTION
**Pull request by alexander-novo**
Fixes magefree/mage#10104 and Fixes magefree/mage#10302

Added a test, and fixed a bug in `printPermanents` for permanents which are attached to something other than a permanent

### CODE REVIEW

**Comment by maximuscesar** [comment]
The problem persists, when the effect resolves the card goes to the graveyard instead of attaching to the next player (in my case, the same player because it's a 1v1 game).

**Comment by alexander-novo** [comment]
@maximuscesar I feel pretty confident that this fix is working. I have added a test for this exact scenario. When you say the problem persists, you mean that you have checked out my branch and built a local copy of the game, and the problem persists on that local copy? Otherwise, this pull request hasn't been merged into main, so it would not be fixed on the beta version, for instance.

**Comment by maximuscesar** [comment]
Oh, sorry. I will wait then.

**Comment by xenohedron** [comment]
Functionality looks good. However, for consistency with surrounding code style, I would prefer to see braces used for if statements.

**Comment by alexander-novo** [comment]
Sure

**Review by xenohedron — APPROVED** [review]

**Pull request merged**
