### PR TITLE
Implement Simic Ascendancy

### PR DESCRIPTION
**Pull request by jmharmon**

### CODE REVIEW

**Comment by theelk801** [comment]
This needs to trigger once off of multiple counters being added rather than multiple times off of a single counter being added. Take a look at Enduring Scalelord and The Ur-Dragon. You can get the amount of counters added with `event.getAmount()`

**Comment by jmharmon** [comment]
I actually based the code off Enduring Scalelord.

**Comment by theelk801** [comment]
Right, but the Scalelord only adds one counter, while this adds multiple. That's why I suggested looking at The Ur-Dragon.

**Comment by jmharmon** [comment]
I've looked at The Ur-Dragon code, it's not making sense. I'm also not sure where event.getAmount() would work in the current code.

**Comment by jeffwadsworth** [comment]
For your event check, you may wish to consider:
GameEvent.EventType.COUNTERS_ADDED
event.getAmount()
etc

**Comment by theelk801** [comment]
It’s alright, I’ve already made the changes and they work. Sorry for being impatient.

**Comment by theelk801** [comment]
It’s alright, I’ve already made the changes and they work. Sorry for being impatient.

**Pull request merged**
