### PR TITLE
Premodern: On July 15th Land Tax got banned

### PR DESCRIPTION
**Pull request by gotoco**
see more details: https://premodernmagic.com/blog/ban-list-update-2023/

### CODE REVIEW

**Comment by xenohedron** [comment]
Hey, it looks like there are other discrepancies in the ban list for Premodern, going by <https://premodernmagic.com/banned-watched#ban-list>. Would you be willing to cross-check the xmage list, and add a comment at the top to the reference source? Please keep it alphabetized as well. Thanks!

**Comment by gotoco** [comment]
Sure thing I will make sure they are inline

**Comment by Susucre** [comment]
https://scryfall.com/search?q=banned%3Apremodern&as=checklist has the banlist in alphabetical order if that helps.

**Comment by gotoco** [comment]
I've added few missing cards (mainly with "playing for ante" rule) but now both lists are inline.

**Comment by xenohedron** [comment]
Ah, turns out that those are already banned in the Constructed class, so that's why they weren't present here as it's technically superfluous. I do think it's easier to cross-reference this way though.

Thanks for the contribution.

**Review by xenohedron — APPROVED** [review]

**Pull request merged**
