### PR TITLE
Add a password user authentication when connecting to servers.

### PR DESCRIPTION
**Pull request by menocar**
Hi!

This is an attempt to add a password user authentication when connecting to servers. Please let me know if you guys are interested in this idea. I'll work on more details if I can get positive feedback from you guys.

The background for this pull request: this allows users to prove their long term identity so that we can record their past match histories without worrying about user name conflicts and/or impersonation. This will also be the foundation for the future works for preventing bad user behaviors by allowing us to record their past flagged acts. Such a user can still create a new account, but people can chose to have matches only with users with good past histories.

Some comments on this pull request:
* Authentication data is stored in a new H2 database.
* Passwords are stored after being hashed by SHA-256, so leakages are less of a problem.
* I chose Apache Shiro (http://shiro.apache.org/) as an authentication framework.
* I haven't yet added 1) a sign-up flow and 2) a password change flow.

Some potential TODOs:
* Client <-> server connection is currently not encrypted, so passwords are sent in plaintext on the wire. JBos Remoting supports SSL connections, so we can enable it if we want to: http://docs.jboss.org/jbosssecurity/docs/6.0/security_guide/html/chap-Secure_Socket_Layer.html
* Passwords are stored in plaintext in the client. This should not be as problematic as the one above.

Thank you,
Me Car

### CODE REVIEW

**Comment by LevelX2** [comment]
Hello menocar,

we're definitely interested. Thanks for your work and contribution.

I will create and update Xmage first to 1.4.v6v1 (probably tomorrow) on the public servers, before I merge your pull request.

We should discuss under the following issue, what steps still to do to integrate it to a first release:
https://github.com/magefree/mage/issues/478

Regards
LevelX

**Comment by menocar** [comment]
Sounds great! Let's continue the discussion in that issue. Also thank you for adding me to the group.

**Comment by menocar** [comment]
Merging this at the moment might cause a problem on version up. I modified the signature of registerClient so if server / client versions are incompatible the connection attempt fails without a mage version exception so user doesn't know if they need to update their client. Maybe it's better to leave the old registerClient by marking it as deprecated (but old clients can still use it to get a mage version exception), and add a new API for password connection. I'll look into it.

**Comment by LevelX2** [comment]
ok, life ain't easy.

**Comment by menocar** [comment]
Sent the following pull request: https://github.com/magefree/mage/pull/1445

**Pull request merged**
