### PR TITLE
Add additional copy test to check copy of effects/abilities

### PR DESCRIPTION
**Pull request by Susucre**
branch is on top of #10752

### CODE REVIEW

**Comment by xenohedron** [comment]
@Susucre can you rebase this now that the base test has been merged? and leave out the devotion count adjust

**Comment by Susucre** [comment]
done rebasing. Should be good once CI gives the green light.

**Comment by xenohedron** [comment]
doesn't look quite right to me

**Comment by Susucre** [comment]
Ok should be clean now?

**Review by xenohedron — APPROVED** [review]

**Pull request merged**
