### PR TITLE
Add card "Cradle to Grave".

### PR DESCRIPTION
**Pull request by bieno002**
Added card Cradle to Grave.

### CODE REVIEW

**Comment by LevelX2** [comment]
> picture they have displayed of the card has the text I used

The text section is relevant it contains the most recent text we always try to use.

**Comment by bieno002** [comment]
Ok sounds good I'll change that as well.

**Comment by bieno002** [comment]
@LevelX2 , I made the changes you recommended and they appear to be correct.  However, I wasn't able to retest them as I keep hitting an error when trying to run the mage server, it doesn't look to be related to the card changes I made but I can't get past it or figure out what is causing it.  I have done a couple clean and builds and I still hit it.  This is the bt:

org.h2.jdbc.JdbcSQLException: Connection is broken: "unexpected status 5374023" [90067-187]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.engine.SessionRemote.done(SessionRemote.java:637)
	at org.h2.command.CommandRemote.executeQuery(CommandRemote.java:158)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:108)
	at com.j256.ormlite.jdbc.JdbcCompiledStatement.runQuery(JdbcCompiledStatement.java:55)
	at com.j256.ormlite.stmt.SelectIterator.<init>(SelectIterator.java:55)
	at com.j256.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:247)
	at com.j256.ormlite.stmt.StatementExecutor.query(StatementExecutor.java:196)
	at com.j256.ormlite.dao.BaseDaoImpl.query(BaseDaoImpl.java:265)
	at mage.cards.repository.RepositoryUtil.isDatabaseObsolete(RepositoryUtil.java:26)
	at mage.cards.repository.ExpansionRepository.<init>(ExpansionRepository.java:41)
	at mage.cards.repository.ExpansionRepository.<clinit>(ExpansionRepository.java:23)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:62)
	at mage.server.Main.main(Main.java:116)
Exception in thread "main" java.lang.NullPointerException
	at mage.cards.repository.ExpansionRepository.add(ExpansionRepository.java:56)
	at mage.cards.repository.CardScanner.scan(CardScanner.java:62)
	at mage.server.Main.main(Main.java:116)

**Comment by LevelX2** [comment]
Thanks for your contribution.

**Pull request merged**
