### PR TITLE
Implemented Hydromorph Guardian

### PR DESCRIPTION
**Pull request by edgao**
First time contributing - just want to make sure things work.

### CODE REVIEW

**Comment by edgao** [comment]
Aaand now I feel pretty dumb. Should be fixed - most of this code is c/p-ed out of `scarsofmirrodin.TurnAside`.

**Comment by LevelX2** [comment]
I guess you should create a custom predicate object instead of a custom target object.
Example could be NumberOfTargetsPredicate.

**Comment by LevelX2** [comment]
Thanks for your contribution.
I made the suggested switch to a custom predicate. I had to implement also some changes to the framework for this.

**Comment by edgao** [comment]
Ah, sorry - I was pretty busy yesterday and didn't have time to work on this. Looks like it was a pretty complicated switch; what was the reasoning behind making the change?

**Comment by LevelX2** [comment]
Creating a Predicate is more simple and less complicated than a target class. Creating a custom target class can easily create AI problems in handling this custom class.

The switch was only complicated because the TargetSpell class did not support yet the used predicate object that also provides the sourceId of the involved stack object. I added this with this change so it's available now also for all further predicates that act with the TargetSpell class.

**Pull request merged**
