### PR TITLE
Fix Brawl.java banlist comments

### PR DESCRIPTION
**Pull request by brikr**
These cards were banned in 2018

### CODE REVIEW

**Comment by spjspj** [comment]
If you'd like to, could also fix standard.java where I copied them from :)

**Comment by brikr** [comment]
@spjspj I didn't realize these were just copied from there. Is there a better way we could do this since Brawl will always share Standard's banlist? (or will it be separate and I'm just imagining things?)

**Comment by spjspj** [comment]
Yeah, would be better to refactor them :)

**Comment by brikr** [comment]
@spjspj FWIW, I just saw the results for last week's Brawl challenge on MTGO and the metagame is very narrow. I wouldn't be surprised if it splits into having its own banlist, so I'd say we avoid refactoring for now.

**Pull request merged**
