### PR TITLE
Chronozoa card implementation and test

### PR DESCRIPTION
**Pull request by glerman**
first commit for me

### CODE REVIEW

**Comment by LevelX2** [comment]
I don't see your commt here.
It can't be merged automatically. I recommend to make a new clone.
Add to the new clone your Chronozoa source code and create a pull request with only the Chronozoa.

Alternate you can post the code to the developer forum but the new clone would be the best solution I guess.

**Comment by LevelX2** [comment]
Anyway it shouldn't be merged to Network_Upgrade branch but master branch.
Maybe that ist the reason of the problems.

**Comment by glerman** [comment]
I changed to Network_Upgrade because the "Create pull request" was disabled
to master.
Anyway, I didn't even see my code in the pull request I created, did you
see it?

I Also tried the command line "git pull-request origin
https://github.com/magefree master"
and the output looked promising, but I don't think it made it's way to the
server

**Comment by LevelX2** [comment]
Make a new Fork of the repository.
Add to the fork your Chronozoa class copy the source code from your object now and create a pull request with only the Chronozoa.

**Comment by glerman** [comment]
Ok, I'll try it later :)

**Pull request closed without merging**
