### PR TITLE
[MID] Implemented Teferi, Who Slows the Sunset + Emblem

### PR DESCRIPTION
**Pull request by LePwnerer**

### CODE REVIEW

**Comment by theelk801** [comment]
is there a reason you're implementing this on the daybound/nightbound branch and not the master branch?

**Comment by LePwnerer** [comment]
Sorry, this is my first time contributing to any git repo in a team, ain't used to branches.

**Comment by theelk801** [comment]
it's alright, just create a separate branch for each card and open a pull request for each of them so they can be reviewed separately

**Comment by LePwnerer** [comment]
ah, ok will do ^^

**Pull request closed without merging**
