### PR TITLE
Feature/Add Set Selection filtering 

### PR DESCRIPTION
**Pull request by salco**
new pull request base on the last one, #4708

### CODE REVIEW

**Comment by salco** [comment]
Dont know what mean this conflict with the 2 file?

**Comment by JayDi85** [comment]
Your branch too old (missing 700 commits from xmage master). You need to update it by your IDE or github to latest version and fix merge conflicts (the best one -- rewrite conflicts files by xmage master and add your changes to it).

shot_180423_182320

**Comment by salco** [comment]
Ok, I dont know if it work I will check at the result from travis. It was my first time merging file to update a branch

**Comment by LevelX2** [comment]
Thanks for your contribution! 😃

**Pull request merged**
