### PR TITLE
Removed erroneous check in dark deal effect

### LINKED ISSUE #10257: Dark Deal doesn't discard a player's hand if they only have one card in hand
[[Dark Deal]] has this erroneous check:

https://github.com/magefree/mage/blob/7e3e430202cc105f2b3922721864295500a5eb1d/Mage.Sets/src/mage/cards/d/DarkDeal.java#L65

### PR DESCRIPTION
**Pull request by alexander-novo**
Fixes #10257

### CODE REVIEW

**Comment by alexander-novo** [comment]
[[Dark Deal]]

**Comment by Grath** [comment]
Perhaps have an `if (cardsInHand > 0) { }` around the two lines? The code was incorrected in https://github.com/magefree/mage/commit/491fc560e846be1445818dd34076d02fd09d57f1 because of a null pointer exception with effects that attempted to wheel away empty hands.

**Comment by JayDi85** [comment]
@Grath that's right, must be `cardsInHand > 0`

**Comment by alexander-novo** [comment]
I fixed it. What's the difference between this and how it's done in windfall?

https://github.com/magefree/mage/blob/e176292da60dcd06be17286c181c99578b834756/Mage.Sets/src/mage/cards/w/Windfall.java#L59

**Pull request merged**
