### PR TITLE
[BRO] Implemented In the Trenches

### PR DESCRIPTION
**Pull request by weirddan455**
Added a new class plus logic to `ActivatedAbilityImpl` to handle "once per game" activated abilities.

### CODE REVIEW

**Comment by theelk801** [comment]
can you integrate these changes into [[surge engine]]?

**Comment by weirddan455** [comment]
> can you integrate these changes into [[surge engine]]?

Sure, I think that one still needs its own ability class for the "is blue" condition and text but I can remove the methods you wrote for the once per game logic.

**Comment by weirddan455** [comment]
Done with the commit I just pushed.

**Comment by theelk801** [comment]
we'll probably want to add more common classes but this is fine until we see more abilities like this

**Pull request merged**
