### PR TITLE
Fix Shockmaw Dragon's damage trigger

### PR DESCRIPTION
**Pull request by Grath**
The previous implementation was very wrong. This implementation is copied from Balefire Dragon's, except dealing one damage rather than the same amount as the damage dealt to the player.

### CODE REVIEW

**Comment by theelk801** [comment]
thanks for the PR

**Comment by jeffwadsworth** [comment]
This should have just been reverted to the previous working version.

**Comment by theelk801** [comment]
Oh that's my bad, sorry

**Comment by jeffwadsworth** [comment]
All good.

**Pull request merged**
