### PR TITLE
Implemented card: Casting of Bones

### PR DESCRIPTION
**Pull request by AMWJ**
Would appreciate comments.

### CODE REVIEW

**Comment by Zzooouhh** [comment]
Older cards from non-numbered sets usually follow the numbering scheme from magiccards.info. Following this scheme, Casting of Bones should be numbers 2 and 3.

**Comment by JayDi85** [comment]
@Zzooouhh current xmage version support card number changes (backward compatibly with old record in decks files, etc) -- no need to use old style numbering.

**Comment by LevelX2** [comment]
Good move to create the common class. Thanks for your contribution.

**Comment by LevelX2** [comment]
Did some minor changes to the code here: https://github.com/magefree/mage/commit/1e1e361c600b5368c6013460711132c3396aefcd

**Comment by AMWJ** [comment]
Excellent! Could you please explain why you removed the discard ability from Casting of Bones? I don't have a great understanding of when that's necessary.

**Comment by LevelX2** [comment]
I didn't removed a discard ability. I removed the second attachEffect.
You added two attachEffects. That's not correct. The Outcome information is only a information for the AI help to decide if an spell/ability is good or bad for the target. It does only use one outcome.

**Comment by AMWJ** [comment]
Alright, makes sense.

**Pull request merged**
