### PR TITLE
[WOC] Implement Timber Paladin

### PR DESCRIPTION
**Pull request by xanderhall**
Manually tested effect, abilities worked correctly

### CODE REVIEW

**Comment by xanderhall** [comment]
[[Timber Paladin]]

**Review by xenohedron — APPROVED** [review]
I don't think the check for Auras is really necessary. There aren't other enchantment types that attach to permanents. (Kitsune Mystic is the only previous card checking two or more using this EnchantedSourceCondition class.)

**Comment by Susucre** [comment]
@xenohedron I have not look fully at everything, but couldn't equipements become enchantments? Like with [[Enchanted Evening]]. The attachement code being shared between them, does the Condition only checks auras? I think that is slightly bugged for those edge cases.

**Comment by xenohedron** [comment]
Great point @Susucre . A very niche edge case! I guess Kitsune Mystic should be updated to use this new aurasOnly parameter

**Pull request merged**
