### PR TITLE
[LTR] Implement Delighted Halfling

### PR DESCRIPTION
**Pull request by Susucre**
Took a lot of inspiration from Cavern of Souls (apart from the type choosing).

### CODE REVIEW

**Comment by Susucre** [comment]
[[Delighted Halfling]] [[Cavern of Souls]]

**Review by xenohedron — APPROVED** [review]
by the way I notice your imports are organized a bit differently than most of us, it's not a big deal but if you can align with the IntelliJ default that can help reduce merge conflicts in the future.

**Comment by Susucre** [comment]
@xenohedron just to be sure, I have tweaked my settings into
importIntelliJ

Does that correspond to what the other devs are using? At the moment I only use IntelliJ (or java) for xmage development, so I do not mind tweaking that further.

**Comment by Susucre** [comment]
Alright found another relevant setting in Code Style > Java > Imports > Import Layout, where I had import java separate from others import. Grouping them with the other imports, as this seems to fit better with the codebase.

**Comment by xenohedron** [comment]
The key thing is to _deselect_ "optimize imports on the fly" as that can potentially add lots of noise when making smaller changes (like adjusting filters or minor text fixes). OK to optimize imports when rewriting/adding/removing multiple lines of code (like refactoring to common class)

I believe these days we're defaulting to list java imports below mage imports, but there's a lot of legacy code written by lots of different devs without much of a style guide. The reference <https://github.com/magefree/mage/wiki/Setting-up-your-Development-Environment#code-style-and-formatting> isn't very detailed. I'd say try to match style to recent cards by theelk801, if you can.

**Pull request merged**
