### PR TITLE
[do not merge] Fix missing art of double-faced variant cards

### PR DESCRIPTION
**Pull request by sprangg**
The double-faced cards that have different art variants within the same set are currently either showing no back side art, or showing the wrong back side art (depending on situation).

This is because of two issues that this PR fixes:
- The variant back side art doesn't get downloaded. This is fixed in the commit to ```DownloadPicturesService.java```.
- The cards with variant art initially store the wrong ```cardNumber``` value for their ```secondSideCard```. This is fixed in ```CardImpl.java``` by making sure that the ```cardNumber``` of the front and back side are the same for cards with variant art.

I'd like to note that I tried several ways to fix the latter issue, but this was the only way that worked. For some reason the ```cardNumber``` for the back side still becomes wrong if it's corrected at the ```createCard``` stage in ```getSecondCardFace```, where it'd make the most sense to fix it.

In any case, I consider this solution good enough. Fixes https://github.com/magefree/mage/issues/9701

### CODE REVIEW

**Comment by sprangg** [comment]
@JayDi85 May I ask why you don't want this merged? You want to examine/test it first?

**Comment by JayDi85** [comment]
I already have some changes for NPE fixes in MDF cards drawing (second side switch bug). It's not finished yet but beta releases has it. So I need compare and combine it with that PR.

**Comment by sprangg** [comment]
Damn, your case sounds quite similar indeed! I've never personally bumped into an MDF card suffering from the second side having wrong or missing art, but hopefully you can make some sense of this whole thing.

Let me know if you have any questions. I tried to explain things as well as possible in the PR and comments, but this case was a little strange with the way I had to correct the ```secondSideCard``` cardnumber at a late stage, with the new ```setCardNumber``` function right before the card is flipped, to make the fix have an effect.

For extra details: The wrong backside art appears in the deckbuilder, whereas the missing backside art issue happens ingame. And the fix in this PR fixes both cases.

**Comment by sprangg** [comment]
@JayDi85 I'll fix the conflict today that came from the meld DowloadPicturesService change you made

**Comment by JayDi85** [comment]
Original problem was in wrong second side card searching (it's ignore card number, so returns only 1 second side all the time). Fixed by 4e9ffdfaf95521ad402e2d87904d7869fe4e7a35. No needs in that PR any more, but thx for research.

**Comment by sprangg** [comment]
@JayDi85 Awesome, thanks for the fantastic work! 👍👍👍

**Pull request closed without merging**
