### PR TITLE
[Test Coverage Tracking] Added coveralls integration

### LINKED ISSUE #8246: Integrate code coverage into Travis pipeline and GitHub PR workflow
This is a follow-up to #6875. Related to https://github.com/magefree/mage/commit/d481172eb4ce193e84156a88339dfdddb2865af9.

Now that coverage exists, we need to upload the results to a service that will track the coverage over time and that integrates with GitHub to share the progress in the pull requests.

The 2 I most commonly come across are:

* https://coveralls.io/
* https://about.codecov.io

Both have integrations and examples showing how to integrate into your current Travis workflow. Here are links to the related maven plugins:

* [Coveralls plugin](https://github.com/trautonen/coveralls-maven-plugin) / [example PR output](https://github.com/sinonjs/sinon/pull/2010#issuecomment-486888728).

* [CodeCov plugin](https://github.com/codecov/example-java) for Jacoco / [example PR output](https://github.com/sinonjs/sinon/pull/2382#issuecomment-858286228)
   
 I believe the first step is to setup an account with one of the selected services. I can do the work of adding the plugins and such, but an admin would need to setup the project in Coveralls or CodeCov and supply any API keys or related artifacts.

### PR DESCRIPTION
**Pull request by fearphage**
Fixes #8246

This needs an admin to setup a https://coveralls.io account and update the referenced repo token in the code.

### CODE REVIEW

**Comment by fearphage** [comment]
> [ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report (default-cli) on project mage-root: Processing of input or output data failed: Report submission to Coveralls API failed with HTTP status 422: Unprocessable Entity (Couldn't find a repository matching this job.) -> [Help 1]

@JayDi85 Did you ever click buttons on the coveralls site to add this project?

**Comment by JayDi85** [comment]
Yes. It sends something: https://coveralls.io/builds/43239474

**Comment by fearphage** [comment]
> Yes. It sends something

That was from the `github-actions` branch (#8248). This one failed due to the error message above.

**Comment by xenohedron** [comment]
Closing as per #8246, sonar to be run manually on occasion due to large size of project

**Pull request closed without merging**
