### PR TITLE
Implementing Adventures (WIP, do not merge)

### PR DESCRIPTION
**Pull request by theelk801**
All the adventure cards are implemented already, but the adventure parts don't actually work. We have several goals:

- [ ] Make adventures castable from all the correct zones, such that they're treated as instants/sorceries when on the stack and nowhere else
- [ ] Implement the effect that exiles them and allows them to be cast from exile, but only as creatures
- [ ] Some sort of visual component? I'm not really sure how to accomplish that part at all.

I'd really appreciate some help on this.

### CODE REVIEW

**Comment by apetresc** [comment]
@theelk801 Is commit c950feb at all related to this PR? Or was it meant to be rebased from somewhere else?

(Just trying to wrap my head around how I can help with the implementation, but the current diff confuses me since it seems 90% unrelated)

**Comment by theelk801** [comment]
I was just trying to understand how to make things work and cleaning up the code helped make it more readable (to me, at least). Nothing about should be functionally different.

**Comment by jmharmon** [comment]
Would the code be something similar to the Bestow ability? Mechanically it seems similar, it's a creature card with a different cost that is different spell type and aren't split cards.

**Comment by fwannmacher** [comment]
What about using it as a split card? Then the main side could have a flag informing if it is playable from exile or not. The only thing which is needed is changing the flag value when the adventure resolves and when the main side resolves

**Comment by beardstorm** [comment]
Any further progress on this?

**Pull request closed without merging**
