### PR TITLE
[NEO] Implemented Risona, Asari Commander

### PR DESCRIPTION
**Pull request by weirddan455**
Adding/removing counters works.  I'm not sure how many times per combat the second ability is supposed to trigger though.  Currently it's triggering once per creature attacking.  Is this correct?

risona

### CODE REVIEW

**Comment by Alex-Vasile** [comment]
Check out [[Vengeful Pharaoh]]. But it looks like if all the combat damage happens simultaneously, then it should could as a single trigger

"If multiple creatures deal combat damage to you simultaneously, Vengeful Pharaoh will only trigger once. (2011-09-22)"

**Comment by theelk801** [comment]
I'm pretty sure you it only triggers once per damage step, you can probably use `DamagedPlayerBatchEvent` for this.

**Comment by weirddan455** [comment]
@theelk801 Thanks, that fixed it.  Look good now?

**Comment by theelk801** [comment]
yeah looks good to me

**Pull request merged**
