### PR TITLE
Some requested cards implemented 

### PR DESCRIPTION
**Pull request by markedagain**

### CODE REVIEW

**Comment by LevelX2** [comment]
Rest looks good ...

**Comment by markedagain** [comment]
Ready to go!

**Comment by LevelX2** [comment]
Made some fixes and commited with this 
b41c4822e989f847b7aa0b46fca477b29842c180
Check if this makes sense for you.

**Comment by markedagain** [comment]
@LevelX2 :( yup, let me redo this and actually test them before sending it off. i now remember why i had went down the class route since creating the power and toughness during the card implementation is in fact wrong

**Pull request merged**
