### PR TITLE
Implemented Gorm the Great

### PR DESCRIPTION
**Pull request by Zzooouhh**

### CODE REVIEW

**Comment by theelk801** [comment]
Also thank you so much for doing this.

**Comment by Zzooouhh** [comment]
Yes, from what I tried it worked fine. I was wondering whether I missed any important checks in the Combat class.

**Comment by theelk801** [comment]
When it comes to things like this, I just figure there's gonna be a bug report about it at some point. We don't exactly have QA people to catch stuff.

**Comment by Zzooouhh** [comment]
I'm always wary about making alterations to that monstrous checkBlockRequirementsAfter method, so I figured some proofreading could be important. I'll be merging it then.

**Pull request merged**
