### PR TITLE
AI: End Basalt Monolith self-infinite loop by making AI not use untap…

### LINKED ISSUE #10197: AI keeps spamming Basalt Monolith untap ability
The Ai keeps spamming the untap ability of Basalt Monolith, resulting in stalled games

### PR DESCRIPTION
**Pull request by Ebola16**
… ability
Hopefully fixes #10197 #2023

Let's see if this will be the end of the infamous Basalt Monolith bug. The AI will not use the untap ability. This approach at least doesn't make Basalt Monolith completely useless.

### CODE REVIEW

**Review by xenohedron — COMMENTED** [review]
Why do you need to add a whole new set of constructors for this? Can't you just use the existing `addCustomOutcome()`?

**Comment by JayDi85** [comment]
It make card useless for ai (will never untap) and hide a real problem with repeat actions. I don't like that style of fixing.

**Comment by Ebola16** [comment]
I didn't know about `addCustomOutcome()` but that would have worked. This PR is also not useless for the AI since Basalt Monolith can still be tapped once by the AI. Dealing with repeating actions in another PR shouldn't stop a fix for a game-breaking but in my opinion.

**Comment by Ebola16** [comment]
Would a system where the untap ability can only happen once per turn be acceptable?

**Pull request closed without merging**
