### PR TITLE
Fixed NullPointerException when Accursed Witch transforms

### PR DESCRIPTION
**Pull request by brikr**
Feedback issue: #5529
Aura replacement code tried to remove the second face from the original zone which had ownerId == null. Now, we remember the first face (the original card) and remove it from the old zone before creating a permanent out of the second face.

### CODE REVIEW

**Comment by jeffwadsworth** [comment]
The card still doesn't work.  Note that the transformed card does not reduce by 1 spells targeting the player.

**Comment by brikr** [comment]
Thanks for the heads up. I'll fix that as well and add it to this PR.

**Comment by brikr** [comment]
@jeffwadsworth ready for review again.
We shouldn't have been relying on Aura Replacement effects here in the first place, because Accursed Witch's death trigger should target an opponent. I've updated it to work this way now.

Technically, ea0d1b54 is no longer necessary to avoid NPE with this card, but I think it should stay in case future cards involve returning transforming auras to the battlefield.

**Comment by jeffwadsworth** [comment]
Great work.

**Pull request merged**
