### PR TITLE
Added functionality to test AI playing specific commander decks against itself

### PR DESCRIPTION
**Pull request by Alex-Vasile**
As part of testing for #8968.

Putting it here to get some feedback on the approach. I followed along with the existing code, but I don't understand a good portion of it. (Will have to get that documented)

Next step is to get debug printout of every decision that the AI is making to see why it takes too long.

**Question:** The docstring for the class says to use `-Ddebug.mage` to stop timeouts between the client and the server. Where do I add this?

### CODE REVIEW

**Comment by JayDi85** [comment]
1. Do not enable random ai games in the tests

2. Do not copy-paste game engine code (load test code) -- use same method
with new settings. Look at deck colors costants in the start -- you can use
same approach. I can add additional code to custom deck from the file
instead random.

3. Use game config to enable ai debug -- it's documented.



сб, 28 мая 2022 г., 05:58 Alex Vasile ***@***.***>:

**Comment by Alex-Vasile** [comment]
> 1. Do not enable random ai games in the tests 2. Do not copy-paste game engine code (load test code) -- use same method with new settings. Look at deck colors costants in the start -- you can use same approach. I can add additional code to custom deck from the file instead random. 3. Use game config to enable ai debug -- it's documented. сб, 28 мая 2022 г., 05:58 Alex Vasile ***@***.***>:
> […](#)

1. Fixed, that was an oversight on my part.
2. 
    1. I will see about refactoring `playTwoAIGame` and `playAICommanderGame` together and take more parameters so that they share functionality.
    2. "Look at deck colors costants in the start -- you can use same approach." I don't understand.
3. Documented where?

**Comment by JayDi85** [comment]
**About custom deck**

Custom deck supports added by a62f29a7c970a7d243b61b7f3c5c2cf80c21d0b2, use const values at the start to change sets, random or custom deck file for load test. Also added commander game mode as default (decks without sideboard are equal to normal two player game).

shot_220529_013808


**About AI and other logs settings**

Docs:
- `\Mage.Server\release\config\readme.txt`
- `\Mage.Server\config\dev_readme.txt`
- `log4j.properties`

Settings:
- for unit tests: change `\Mage.Tests\src\test\resources\log4j.properties` (AI logs enabled in unit tests by default)
- for runtime server: change `\Mage.Server\src\main\resources\log4j.properties`
- for real server: run with additional param `-Dlog4j.configuration=file:./config/log4j.properties`

Example:
shot_220529_002859

**Comment by Alex-Vasile** [comment]
No longer needed

**Pull request closed without merging**
