### PR TITLE
New Cards

### PR DESCRIPTION
**Pull request by markedagain**
Cards: Mwonvulia Acid Moss, Harvest Wurm, Barbed Shocker, Cabal Slaver, Shoker
effect: DiscardHandDrawEffect
cost: ReturnToHandFromGraveyardCost (this one might be overkill and should of been put directly into card implementationi think unlike the effect that has many cards that use the same effect)

### CODE REVIEW

**Comment by markedagain** [comment]
ill make the changes and do another pull request, thx

**Comment by markedagain** [comment]
ok cool, thank you for the extra tips and pointing out the mistake of the cabal guy and the text changes, sorry still trying to wrap my brain around most of it, i figure the commits will get better and better as time goes

**Comment by markedagain** [comment]
also, is there a better constant then 'TargetController' to designate targetplayer.me .any .all .opponent ?

**Comment by LevelX2** [comment]
> also, is there a better constant then 'TargetController' to designate targetplayer.me .any .all .opponent ?

I guess no. For the "that player" use the effect.setText() or add an additional argument to the effect.

**Pull request closed without merging**
