### PR TITLE
Fixing Icon of Ancestry ability

### PR DESCRIPTION
**Pull request by SpeedProg**
this should fix problems in  #6333 
Also fixes that you where able to chose the order of the cards going at the bottom of the library while it should have been random

### CODE REVIEW

**Comment by emerald000** [comment]
Isn't the creature type predicate applied in two places? In the filter definition and the effect?

**Comment by SpeedProg** [comment]
I don't think so. When the filter is created it only has the the predicate for the creature type (I don't think at this point we know which subtype the player will choose).
And only when the effect is applied I add the chosen subtype.

**Comment by emerald000** [comment]
Does the boost effect use the chosen creature type? Because that effect only uses the predicate from the filter creation.

**Comment by SpeedProg** [comment]
ah I get what you mean. only I will look into it. I totally didn't realize that one. Thank you.

**Comment by SpeedProg** [comment]
nvm it still needs the class because I can't set the outcome otherwise and I assume setting that to AIDontUseIt is important :)

**Comment by emerald000** [comment]
You can use Effect.setOutcome() to set the outcome in the card constructor.

**Comment by SpeedProg** [comment]
So I can't use the predicate like it does for the Permanent selection since, the filter for the cards from library selection does not get called with a PlayerSourceObject but with a PlayerObject that does not have a source. So I don't see how I could get around making an extra class for applying the subtype any more.
it gets called from
HumanPlayer.choose:649
CardsImpl.count:102
FilterCard:57
If I would wanna have a source object, I could maybe imagine getting in some where up that chain, but I don't think changing all this stuff is a good idea. :)

**Pull request merged**
