### PR TITLE
Partially Implments Streets of New Cappena Rebalanced (17 out of 43 cards) 

### PR DESCRIPTION
**Pull request by chesse20**
~~I started this a while ago and then gave up on it so there are some merge conflicts with ScryfallImageSupportCards i don't know how to fix easily.~~
nevermind the merge conflicts were easily handled on githubs merge conflict editor.

Partially implements 17 out of 43 cards from the rebalanced streets of new cappena cards

### CODE REVIEW

**Comment by theelk801** [comment]
I think I'd rather we didn't do the rebalanced cards at all, I don't think they have much demand and I don't like the debt they add either. I'm sorry, I know you've already put in the work for this.

**Comment by chesse20** [comment]
its fine, most of this was done in a few days and then i put it off for a long time and then added the 5 manafixers today.

**Comment by sprangg** [comment]
I'd like to come forth as someone who has demand for a specific rebalanced card: The buffed version of [Dungeon Descent](https://scryfall.com/card/afr/A-255/a-dungeon-descent) will likely be needed for a rebalanced Forgotten Realms set of mine. The original version of that card is simply awful.

Would be nice if we had some way to include these in XMage.

**Comment by chesse20** [comment]
yeah i was originally planning on having the rebalanced snc set to draft with, mostly i wanted to make the "Givemanaandcastsourceability" have more options so i could use the mechanic in a custom set i was planning on adding

**Pull request closed without merging**
