### PR TITLE
Fixed Release to the Wind not allowing to cast the exiled permanent

### PR DESCRIPTION
**Pull request by weirddan455**
Issue #7415 

I think this was a zone change counter issue.  Other cards using this method are cards that exile from top of library while Release to the Wind is passing it a Permanent.  I tested that this fixed it and didn't break other cards that use it (tested with Mind's Desire) but wanted to send a PR to double check this is the correct way to fix the problem.

### CODE REVIEW

**Comment by JayDi85** [comment]
1. You cant apply effect to all cards in the exile zone (it can contains non related objects from other effects). Must be filtered for input cards only.

2. It work with cards so call exileAndPlayFromExile from Release to the Wind with card param like game.getCard. Permanent from the battlefield is PermanentCard and it exists on battlefield only. I dont think what that PR changes needs.

Please try to fix Release to the Wind by card using -- is it working or not?

**Comment by weirddan455** [comment]
@JayDi85 I tried using `game.getCard` in Release to the Wind and passing that.  It was buggy.  It left the card still sitting on the battlefield (did not go to exile) but also popped up the exile window and let me cast it again.

Would the exile zone be able to contain unrelated objects even with the exileId that's generated here?

https://github.com/magefree/mage/blob/b5495a6465d54e73aa26c10bc77f456231f8aadc/Mage/src/main/java/mage/abilities/effects/common/asthought/PlayFromNotOwnHandZoneTargetEffect.java#L147-L151

**Comment by JayDi85** [comment]
Yes, it generates source related exile zone. Even without zcc (zcc is xmage's workaround to reset card as a new object after zone change). So another cards can be potentially puts cards here (from same object after blink, from same or another ability, etc). 

I'll research that bug and response here later (is it fine or need improves).

**Comment by JayDi85** [comment]
Original problem was in `PlayFromNotOwnHandZoneTargetEffect` -- it doesn't support permanents as a target. If you target a permanent on battlefield then game return `PermanentCard` or `PermanentToken` -- it still a `Card` interface, but not a real card (use `getMainCard` to find a real `Card` object from it). 

Also `PlayFromNotOwnHandZoneTargetEffect` didn't make a difference between "play card" rule text (can play land and cast spell) and "cast card" rule text (can't play land but can cast spell).

It was fixed by 2d96d36ec8c24344b6219e72fe68d1df24b8a773. 

Related changes for that issue:
shot_210131_223700
shot_210131_223846

**Pull request closed without merging**
