### PR TITLE
Fix the issue that on reconnect client didn't send password.

### PR DESCRIPTION
**Pull request by menocar**
Also changed the dialogs to use server/port values from the connect dialog.

### CODE REVIEW

**Comment by menocar** [comment]
Good point. Probably for some subset of pref values we should have a server address as a secondary key. What's a bit complicated though is unless you want to explicitly have a different config per server, you probably want to use the same value everywhere, but if you don't have a single connection prefs we don't know which ones to use as defaults on the next connection to a new server. I guess we can 1) look up the server address from the pref, which we'll have only one value, and 2) use the pref values associated with the server. That allows us to always use the set of pref values used on the previous connection.

**Comment by menocar** [comment]
Committed a change to save userName and password per server.

**Comment by menocar** [comment]
And also email. Also now we save user input in RegisterUserDialog and ResetPasswordDialog to pref. They are loaded when server is changed in ConnectDialog too.

**Comment by LevelX2** [comment]
> And also email. Also now we save user input in RegisterUserDialog and ResetPasswordDialog to pref. They are loaded when server is changed in ConnectDialog too.

Sounds good.

**Pull request merged**
