### PR TITLE
Implement Harsh Mercy

### PR DESCRIPTION
**Pull request by pcasaretto**
Used Patriarch Bidding's code as a template.

### CODE REVIEW

**Comment by pcasaretto** [comment]
Have not tested.

**Comment by LevelX2** [comment]
You should test, it's so easy to forget something.
What's the reason you did not test your work?

**Comment by pcasaretto** [comment]
> You should test, it's so easy to forget something.
> What's the reason you did not test your work?

A bit of rush and laziness, heh. Sorry about that.
Card tested and suggestions implemented!

**Comment by LevelX2** [comment]
Looks good now. Thanks for your contribution.
If you like to have a profile for the card tracker tool (http://ct-magefree.rhcloud.com/) to mark the cards you are going to implement, let me know your forum profile (http://www.slightlymagic.net) or an email adress, so I can send you the profile information.

Regards

**Comment by LevelX2** [comment]
Had to add a fix for the continue statement. 
Like it was it did not continue the player iteration. fbb02760aa1429f720a0494be1451526b52e6859

**Comment by pcasaretto** [comment]
Oops, sorry about that.
About the profile, you can send it to pcasaretto@gmail.com

**Pull request merged**
