### PR TITLE
pelt collector counters

### PR DESCRIPTION
**Pull request by gp66**
pelt was not getting counters

### CODE REVIEW

**Comment by gp66** [comment]
all my checks passed, any ideas why it failed here?

**Comment by JayDi85** [comment]
Tests are fine. Please, provide steps to reproduce your bug with counters. Old code line uses all around xmage (hundreds of places), but new code line uses in one place only.

**Comment by gp66** [comment]
i shot a quick video from the latest beta release.
[https://youtu.be/nk97ZTNxHDc](https://youtu.be/nk97ZTNxHDc)

**Comment by LevelX2** [comment]
Fixed the problem with 50668a548fa34b6c4c344682d1d4a8ece86df832 and 61315ec74107a24e4717e40c29e36fe73ec6f65f. Method getFirstTargetPermanentOrLKI did not handle not inititialized zoneChangeCounters.
The problem was caused because of a not inititialized zoneChangeCounter in FixedTarget and on the other side using the unspecfic target setting with only an id to an permanent which should be avoided if possible.

**Pull request closed without merging**
