### PR TITLE
[LTR] Implement Stone of Erech

### PR DESCRIPTION
**Pull request by Susucre**
Of note, this PR is grouping together two other recent cards for that exact same replacement effect.

### CODE REVIEW

**Comment by Susucre** [comment]
[[Stone of Erech]] [[Misery's Shadow]] [[Liesa, Forgotten Archangel]]

**Comment by xenohedron** [comment]
[[Gisa, Glorious Resurrector]] has the same ability.
I'd recommend rewriting the common class so it takes a FilterPermanent rather than hardcoding to creatures opponents control. This lets us expand to [[Void Maw]] and [[Lorcan, Warlock Collector]]

**Comment by Susucre** [comment]
> [[Gisa, Glorious Resurrector]] has the same ability.
> I'd recommend rewriting the common class so it takes a `FilterPermanent` rather than hardcoding to creatures opponents control. This lets us expand to [[Void Maw]] and [[Lorcan, Warlock Collector]]

Gisa has a linked ability with the exiled cards, I did not want to mess with it.
Makes total sense to not be specific to creature your opponent control.
I'll refactor that. Probably not before next week though.

**Comment by xenohedron** [comment]
Oh good call, my eyes just skipped over the linked effect. I agree it's best to leave that one alone then.

**Comment by Susucre** [comment]
This does extend the ReplacementEffect "If ... would die, exile it instead", using a `PermanentFilter`.
[[Void Maw]] and [[Lorcan, Warlock Collector]] have thus be refactored to use that instead
of a custom replacement effect.

Added a static filter `StaticFilters.FILTER_ANOTHER_CREATURE` for Void Maw that is filtering "another creature".
Found and refactored cards that were separatly declaring that exact filter locally:
* [[Flame-Kin War Scout]]
* [[Herd Gnarr]]
* [[Mogg Bombers]]
* [[Timid Drake]]

There might be more of that kind of filter, but the search for them is not that easy.

**Comment by xenohedron** [comment]
I apologize... Void Maw also has a linked effect to the exile zone. It might be possible to add a constructor parameter `boolean exileForSource` so that the common effect class can be used for it, but it would also be totally fine to revert that card back to its original custom effect and call it a day.

The rest looks good.

**Comment by Susucre** [comment]
Arf, I did not notice either. I'm reversing for now (keeping the another creature static filter.)

I'll attempt in a future PR on to further refactor those kind of replacement effect.
Another one I had in mind is non-linked that exiles with counters instead of sending to the graveyard like [[Draugr Necromancer]] or [[Ravenloft Adventurer]].

**Review by xenohedron — APPROVED** [review]

**Pull request merged**
