### PR TITLE
 [DON'T MERGE] Reinforcement learning AI

### PR DESCRIPTION
**Pull request by ElchananHaas**
This is a work in progress implementation of a reinforcement learning AI. Instructions on training an AI are in age.Server.Plugins/Mage.Player.RLPlayer/README.md

### CODE REVIEW

**Review by JayDi85 — CHANGES_REQUESTED** [review]
I can see many problems with code and docs. E.g. OpenJDK/Java 11, wrong ignored or jar files, no docs at all (on results and usage). As it is, it will not be merged to main project.

Such big sub-projects must be made and merged steps by steps: from pre-requisite changes to game engine to workable testing server, results and trained models.

**Comment by ElchananHaas** [comment]
@JayDi85 
Thank you far taking the time to look at the patches. I am new to making contributions to open source and I appreciate the feedback. 
If I am understanding you correctly you are saying I should 
1) Take the current master version and make only the required changes to it 
2) Break the modifications up into a series of smaller pull requests
I think I could avoid making any modifications to the rest of the engine except for adding the plugin to the Mage.Server.Plugins pom.xml file. That version would have the capability to train a deep learning model but not to play against it. 
I could in a later pull request once all the training code is good add the ability to have the client play against the AI.
Is this the right approach?

**Comment by JayDi85** [comment]
Yes, that's correct -- make PR for game engine and other code as different PRs (one or few). And add description for each of the changes in PR's post. As example I can see commented/disabled "plugins loading code" without reason.

Please write your plans for code modification and AI training. What's current version can do, what's you plan to do next and hows users (most important) and devs (less important) can use new AI in games and what it can do compared to default AI.

**Comment by ElchananHaas** [comment]
Where should I write the plans? In the README file or in the description of the pull requests or here?

**Comment by JayDi85** [comment]
In PR's starting post. As example: you can write it as TODOs list (what's completed and what's need to be done).

**Comment by JayDi85** [comment]
Any news?

**Comment by ElchananHaas** [comment]
I was on vacation, I am working on making the changes now.

**Comment by ElchananHaas** [comment]
I am working on downgrading my Java version to 1.8 and getting to code to compile with many changes reverted. When I do that I will be ready to make another pull request.

**Comment by JayDi85** [comment]
It's ok to work with Java 9 -- xmage will be migrated to latest openjdk soon (in next months).

**Comment by JayDi85** [comment]
E.g. java 9+ can be part of your AI code. And java 8 can be part of xmage engine changes to support AI (see [comment above](https://github.com/magefree/mage/pull/8100#issuecomment-893644779) about code/pr split).

**Comment by ElchananHaas** [comment]
The issues is I get these errors when compiling. They are due to javaFX not being default in newer versions of java. I am not sure how to make my code depend on the pull request that already adds them.
[ERROR] /home/elchanan/java/mage/Mage.Client/src/main/java/mage/client/dialog/WhatsNewDialog.java:[6,26] package javafx.application does not exist
[ERROR] /home/elchanan/java/mage/Mage.Client/src/main/java/mage/client/dialog/WhatsNewDialog.java:[7,26] package javafx.beans.value does not exist
[ERROR] /home/elchanan/java/mage/Mage.Client/src/main/java/mage/client/dialog/WhatsNewDialog.java:[8,26] package javafx.beans.value does not exist
[ERROR] /home/elchanan/java/mage/Mage.Client/src/main/java/mage/client/dialog/WhatsNewDialog.java:[9,25] package javafx.concurrent does not exist
[ERROR] /home/elchanan/java/mage/Mage.Client/src/main/java/mage/client/dialog/WhatsNewDialog.java:[10,26] package javafx.embed.swing does not exist
[ERROR] /home/elchanan/java/mage/Mage.Client/src/main/java/mage/client/dialog/WhatsNewDialog.java:[11,20] package javafx.scene does not exist
[ERROR] /home/elchanan/java/mage/Mage.Client/src/main/java/mage/client/dialog/WhatsNewDialog.java:[12,24] package javafx.scene.web does not exist
[ERROR] /home/elchanan/java/mage/Mage.Client/src/main/java/mage/client/dialog/WhatsNewDialog.java:[13,24] package javafx.scene.web does not exist
[ERROR] /home/elchanan/java/mage/Mage.Client/src/main/java/mage/client/dialog/WhatsNewDialog.java:[45,19] cannot find symbol

**Comment by JayDi85** [comment]
You can look at main java 9 topic here #6197 -- it contain problem list and fixes. JavaFX for OpenJDK is here: #6703

If you can't use 1.8 then just use that fixes in your local version without pom changes commits. XMage runs fine under 9+ and OpenJDK -- just don't use java 9+ features for game engine fixes. But you can use that features for your AI code (if necessary).

**Comment by ElchananHaas** [comment]
Closing due to opening a replacement pull request.

**Pull request closed without merging**
