### PR TITLE
Create SkyshipWeatherlight.java

### PR DESCRIPTION
**Pull request by myersn024**
Implemented and tested SkyshipWeatherlight.java. The only issue that I ran into was that the card image wouldn't show up in the deck editor. Everything else functioned as intended.

### CODE REVIEW

**Comment by myersn024** [comment]
Added EonHub, as well

**Comment by myersn024** [comment]
I used the code for Stasis as a guide for coding Eon Hub. I don't mind updating it to using ContinuousRuleModifyingEffect if that's what it needs to be.

**Comment by jeffwadsworth** [comment]
Statis just slipped through the cracks when the new ContinuousRuleModifyingEffect code was introduced.

**Comment by myersn024** [comment]
I'll make the necessary changes and initiate another pull once everything is tested.

**Comment by myersn024** [comment]
Also, are the card APIs documented anywhere? I'm used to looking through code, but this project is pretty large and I'm not that great with java.

**Comment by jeffwadsworth** [comment]
Not really.  But the code is pretty straight-forward.  I am an uber-noob at Java also.

**Comment by daagar** [comment]
I've not found the API documented anywhere (generating the javadoc can help a little), but the Netbeans features make it a bit more bearable - make liberal use of alt-shift-o to search for available classes. As an example, alt-shift-o then type *Effect will list pretty much every class related to Effect implemented in-game. 

Granted, you'll now see all these wonderful classes, and have no idea how they really work. Pop one of the classes open, and then right click on the class name and choose 'Call Hierarchy'. You'll get a nice view of every card using the rule/effect/ability in question. Browse through the code of these cards to see how to make use of it. 

This may not be the absolute best way to go about it, but I've muddled through the creation of a number of cards this way (along with using the card tracker database to find other cards that have already implemented similar rules). No offense meant if I'm telling you obvious things!

**Comment by myersn024** [comment]
Thanks for the suggestions, using 'Call Hierarchy' should help a lot.

**Pull request merged**
