### PR TITLE
Freeform Commander

### PR DESCRIPTION
**Pull request by kevinwshin**
Freeform Commander now allows multiple copies of snow-basics. #5242

### CODE REVIEW

**Comment by kevinwshin** [comment]
I'm not sure what you mean about copy-paste from penny dreadful, but I can explain both changes. setupAllowed was deleted as an unused variable (which I think I should've done in a separate commit), and basicLandNames was removed, because it was shadowing an identically named list inherited from mage.cards.decks.Constructed.java which has all nine basics.

**Comment by JayDi85** [comment]
@kevinwshin got it about `basicLandNames`. Dreudful's code -- you can't use more than 1 card for freeform commander (that's wrong and must be deleted):

shot_180825_075258

shot_180825_082620

**Comment by JayDi85** [comment]
Closed via b4fdce53c48212845d88a402be069db6fe1e3659

**Comment by spjspj** [comment]
Why are we removing the singleton nature of freeform Commander?  It's pretty much just freeform, without much commander, at that point.  Would prefer to not have it at all or you could just have 50 fireballs and 50 black lotus.

**Comment by JayDi85** [comment]
@spjspj so that's was not the error with copies? As wiki, [Freeform](https://mtg.gamepedia.com/Freeform):  a sanctioned casual Magic Online format **that allows all sets and cards**... decks can contain any number of copies of a card. There are [singleton format](https://mtg.gamepedia.com/Singleton) for unique card usage.

**Comment by spjspj** [comment]
Freeform is different.  Freeform commander should (in my opinion) be basically commander but with no restricted cards at all.  It goes further and lets and creature or any non-creature Legendary card be your commander as well.

**Comment by JayDi85** [comment]
@spjspj ok, I've revert freeform to singleton format (1bc022a94ae9f9b35c4b23939372b9d4dfc46583). We can change or create the new one later.

**Pull request closed without merging**
