### PR TITLE
Implement Oasis, Wistful Thinking, Magus of the Disk

### PR DESCRIPTION
**Pull request by daagar**
A very simple implementation just to work through the process and learn a bit about XMage development

### CODE REVIEW

**Comment by daagar** [comment]
Okay, this is apparently why I'm a newbie. I didn't realize that adding a new commit would also add to the same pull request - so there are now two cards implemented in this single request. Future implementations will be done on distinct branches so the pull requests can be merged individually.

**Comment by jeffwadsworth** [comment]
1.  Code the card(s) and test them thoroughly.
2.  When done, do a Fetch and then a Pull to update everything.
3.  Select your card(s) and Git->Commit them locally.
4.  Finally, just Push them up to GitHub.

You can push multiple cards/code at once with no problems.


________________________________

**Comment by LevelX2** [comment]
Hello daagar,

thanks for your contribution. Cards look good so far.
Only I wonder if you use the "gen-card.pl" script, because you still have the color setting Wistful Thinking what is no longer needed and not generated by the script.
It's best to use this script, because it reduces bugs that happen while doing it with copy and paste and change the copied code to the new card attributes.
Look here: https://github.com/magefree/mage/wiki/Developer-Getting-Started#perl

I merge the cards.
Thanks again.

**Comment by daagar** [comment]
Ah, thank you for the info! I did indeed use the gen-card.pl script, but I was using another similar card as reference while creating Wistful Thinking and it added a color, so thought maybe that was something not part of gen-card. Will avoid doing that for future implementations!

**Pull request merged**
