### PR TITLE
new cards

### PR DESCRIPTION
**Pull request by markedagain**

### CODE REVIEW

**Comment by fireshoes** [comment]
Make sure you are checking the Cards Page to see what cards others are working on and mark what you are. It helps prevent duplicate work. LevelX can set you up with an account if you need one.
http://ct-magefree.rhcloud.com/

**Comment by markedagain** [comment]
that would be great if i can get an account, i cant see to much info on the general page, was actually unsure how to not duplicate as it already happened once so far

**Comment by LevelX2** [comment]
I need your forum account or an email address to send you the card tracker profile data.

**Comment by markedagain** [comment]
u can send it to markkalender@hotmail.com. also im getting one of my coworkers to help me out with git, i come from svn background having a hard time doing simple tasks

**Pull request closed without merging**
