### PR TITLE
Planar void fix

### LINKED ISSUE #9071: Planar Void triggers on tokens going to the graveyard
[[Planar Void]]

image

### PR DESCRIPTION
**Pull request by alexander-novo**
Fixes #9071

### CODE REVIEW

**Comment by the-red-lily** [comment]
What is being fixed?

**Comment by Alex-Vasile** [comment]
> What is being fixed?

It's supposed to fix the fact that it triggers off of tokens dying. But I do not believe it's doing it correctly. 

It should be refactored to use `PutCardIntoGraveFromAnywhereAllTriggeredAbility`. @alexander-novo will you do the refactor?

**Comment by alexander-novo** [comment]
Sure, I can do that

**Review by Alex-Vasile — CHANGES_REQUESTED** [review]

**Comment by Alex-Vasile** [comment]
Issue solved elsewhere

**Pull request closed without merging**
