### PR TITLE
[NEO] Implemented Scrap Welder

### PR DESCRIPTION
**Pull request by weirddan455**
I made a comment in #8524 regarding an issue I ran into with this card.  Just putting it up here as a work in progress.  Don't merge this yet.

### CODE REVIEW

**Comment by theelk801** [comment]
seems like finding a way to force the player to declare an X value would work in conjunction with a `CostAdjuster` like on [[Aether Tide]], maybe we need a flag we can set on the ability to make that happen

**Comment by weirddan455** [comment]
@theelk801 Thanks, that got me on the right track.  I think using a Variable Cost works best here.  There's no mana cost so it doesn't work quite like Aether Tide.

This gives a prompt to announce the X value first and then sets cost/targets accordingly.  Does this look good to you?

**Comment by theelk801** [comment]
I was thinking there may be some way to get it to ask for an X even though there's no X in the mana cost but if this works then I'm fine with it.

**Comment by weirddan455** [comment]
Well, that's basically what this does.  It asks the player for an X value and then it returns a sacrifice cost with a mana value predicate based on the X value they selected.

If you know of a better way, I'm all ears.

**Comment by theelk801** [comment]
nah this works for me, I think it's good to merge

**Pull request merged**
