### PR TITLE
Add issue templates

### PR DESCRIPTION
**Pull request by allentiak**
I hope this will streamline development...
(When I see the amount of unattended issues here, I feel like I'm drowning in bugs... :-)

@JayDi85 BTW: Could I get developer access? I might help triaging existing bugs...

### CODE REVIEW

**Comment by JayDi85** [comment]
1. No needs in `documentation_update` and `supporter_update.md`;
2. What you mean by "triaging existing bugs"?

**Comment by allentiak** [comment]
On Thu, 7 May 2020 at 11:55, Oleg Agafonov <notifications@github.com> wrote:

>
>    1. No needs in documentation_update and supporter_update.md;
>
> Please, feel free to modify the templates as you see fit. I just think
this might help sorting out issues.



>
>    1. What you mean by "triaging existing bugs"?
>
> Tagging them :-)
There are over a thousand of them, and many (if not most) of them don't
even have a tag, so we don't know what they are about.

**Comment by allentiak** [comment]
BTW: I do think both "documentation update" and "supporter update" would be
nice additions :-)

(Of course, maybe the wording could be improved. In that case, please let
me know about concrete suggestions so we can move forward and see ways to
improve the templates.)

>

**Comment by allentiak** [comment]
@theelk801 Maybe this might help auto-triaging issues when they are opened?

**Comment by allentiak** [comment]
@theelk801 @LevelX2 
In the meantime, I would appreciate if I could get permissions for labeling bugs.

**Comment by allentiak** [comment]
> @theelk801 Maybe this might help auto-triaging issues when they are opened?

_(This is, in order not to need creating any more "tracking tasks"_ à la _#6552.)_

**Comment by JayDi85** [comment]
@allentiak it's not a label problem at all -- it's about manual/unit testing and confirm/unconfirm old reported bugs. You can help to test backlog issues like Zerrisx do.

**Pull request closed without merging**
