### PR TITLE
[WOC] Implement Blightwing Bandit

### PR DESCRIPTION
**Pull request by xanderhall**
Effect copied directly from Predator's Hour with slight formatting changes

### CODE REVIEW

**Comment by xanderhall** [comment]
[[Blightwing Bandit]]

**Comment by xanderhall** [comment]
[[Predator's Hour]]

**Comment by xenohedron** [comment]
Wrong apostrophe in rules text

**Review by xenohedron — APPROVED** [review]
I look forward to some refactoring cleanup from #10573 but this is fine for now

**Pull request merged**
