### PR TITLE
[USG] Implemented 7 cards

### PR DESCRIPTION
**Pull request by hanasu**

### CODE REVIEW

**Comment by LevelX2** [comment]
Thanks for your contribution.

Can you give me an email adress or forum account of slightly magic? 
So I can add you to our card tracker tool and send you the profile data.
http://ct-magefree.rhcloud.com/
Than you can mark cards you are going to implement by yourself and set the card to done if commited. It's used to prevent redundant implementation work.

Regards
LevelX2

**Comment by hanasu** [comment]
Sure, my email is bodowd@worcester.edu. That seems helpful.

**Comment by hanasu** [comment]
@LevelX2 I can't seem to log into the card tracker anymore and I can't find any login information in my email where I thought it was. Would you be able to reset it or remind me what it is now? I would appreciate it. Thanks.

**Comment by LevelX2** [comment]
@hanasu I resend you the mail with the account data.

**Pull request merged**
