### PR TITLE
minor change in test details - Skyline Cascade taps for {U} not {B}.

### PR DESCRIPTION
**Pull request by drmDev**

### CODE REVIEW

**Comment by drmDev** [comment]
Fixed SkylineCascadeTest - was not using addTarget properly (didn't matter in functionality, it just defaulted to the only tapped creature of the opponents). Also added tests for Reflector Mage's interactions with morphs that was reported as a bug. The one case reported as a bug indeed has a failing test with it. I would guess it has to do with you first have to try to cast the spell of a given name before you can declare you want to play it as a Morph so it would then be nameless.

**Comment by drmDev** [comment]
Sorry for all the mess in this commit - it also includes the merges from before. Thought the rebase would have taken care of it. I must have done something wrong in git there.

**Comment by rkfg** [comment]
You could make a separate branch, originating from origin/master, on localhost and cherry pick the required commits one by one. Then reset master to that branch, force push it to GitHub and this pull request will be updated automatically.

**Comment by drmDev** [comment]
@rkfg Sorry for all the questions here, but could you walk me through the process? Right now I created a new branch on "https://github.com/drmDev/mage" as "https://github.com/drmDev/mage/tree/tempfixmage" (tempfixmage). Are there certain commands I need to perform to pick the required commits? Or am I executing some commands to back out some other commits (i.e. the commits that were not mine)? I guess really if you could just walk me through the commands needed to be done from here that would be great so I can get this back to a clean state.

**Comment by rkfg** [comment]
You should do everything on your own machine, no need to create branches on GitHub. So first you do `git checkout -b tempfixmage origin/master` (if it doesn't exist, if it does, check if it points to the same commit as origin/master or do `git branch -d tempfixmage` to delete it and create again as said before), then you look at `git log` and do `git cherry-pick e29c444` and other your own commits you want to publish, one by one. After that you'll have `master` in its current broken state and `tempfixmage` like you want it to be. Ensure you haven't missed some commits and then do `git checkout master` to switch to `master` and `git reset --hard tempfixmage` to move the branch pointer to your fix branch. Then you only should push the updated master with force: `git push -f` and your GitHub repo will be updated as well as this pull request. If something went wrong you can use `git reflog` and reset to some earlier state. No commits are lost if you don't garbage collect but pointers to them could be (sometimes).

**Comment by drmDev** [comment]
I appreciate the time to try to help me here. I did all of the above, cherry-picked the 3 commits of mine relevant to my pull request, and after the reset on master and push with force, neither my repo or this pull request was updated. It still contains all the merge commits. I'll try reflog, but I might just end up closing this pull request and starting from scratch (new local repo, new directory to clone xmage repo into, etc) to get these 3 files back up there. I'll learn to use git correctly someday.

**Comment by rkfg** [comment]
Have you pushed your local master branch to the remote master branch? Make sure you're pushing it to github and not some other repo. You could also do `git checkout master`, `git reset --hard origin/master` and `git pull` to make sure your local master branch is identical to the upstream one. Then rebase your commits (which are available on the temporary branch) on top of master and push to your repo.

**Comment by drmDev** [comment]
Redoing this request... closing.

**Pull request closed without merging**
