### PR TITLE
[WIP] [AFC] Implement Rod of Absorption

### PR DESCRIPTION
**Pull request by Alex-Vasile**
For #7978

### CODE REVIEW

**Comment by theelk801** [comment]
This should probably wait until after #8136 is merged (not sure when that's gonna happen) because it deals with casting from a selection of cards.

**Comment by Alex-Vasile** [comment]
Sounds, good. I'll wait on implementing the cast from exile part until that's done.

(looking at it, I'm not sure what's left to do on it)

**Comment by theelk801** [comment]
if you don't mind I'm gonna take this one on the #8136 branch, I'm already doing [[Invoke Calamity]] there which is pretty similar and I need to do some refactoring to code I've already written.

**Comment by Alex-Vasile** [comment]
> if you don't mind I'm gonna take this one on the #8136 branch, I'm already doing [[Invoke Calamity]] there which is pretty similar and I need to do some refactoring to code I've already written.

No worries, have at it

**Pull request closed without merging**
