### PR TITLE
[STX] Flamescroll Celebrant fix

### LINKED ISSUE #9305: Revel in Silence is bugged
Once a player plays Revel in Silence, no one can't cast spells for remainder **of the game**!

### PR DESCRIPTION
**Pull request by cassius1213**
Closes #9305.

### CODE REVIEW

**Comment by Alex-Vasile** [comment]
These looks like it should fix it.  Did you also test them to see that it works correctly with the fix applied?

**Comment by cassius1213** [comment]
No, I haven't set up a test env yet; I'll withdraw the PR.

**Comment by Alex-Vasile** [comment]
> No, I haven't set up a test env yet; I'll withdraw the PR.

Leave it open. Test it out, and whether or not it works update this PR with any changes that need to be made for this issue.

Thank you for the contribution.

I will squash all the commits when merging, so don't worry about how many commits you have to make.

**Comment by cassius1213** [comment]
I'm sorry, but this is all going to be a little too much for a non-pro like me, so I'll just go back to just poking around the code for fun.

Sorry for messing up the issue tracking!

**Comment by PurpleCrowbar** [comment]
Just tested, can confirm this PR resolves both issues with the card

**Comment by Alex-Vasile** [comment]
> I'm sorry, but this is all going to be a little too much for a non-pro like me, so I'll just go back to just poking around the code for fun.
> 
> 
> 
> Sorry for overextending and messing up the issue tracking!

No worries. All I was asking was for you to start a game against the AI, okay the card, and see if it fixed the reported issue.

If you find anything else feel free to open a issue/PR.

**Pull request merged**
