### PR TITLE
[WOE] Implement Brave the Wilds

### PR DESCRIPTION
**Pull request by Susucre**

### CODE REVIEW

**Comment by Susucre** [comment]
[[Brave the Wilds]]

**Comment by theelk801** [comment]
I'm pretty sure this ability should only have a target if it was bargained

**Comment by Susucre** [comment]
Maybe there is something weird with when the choice to bargain happen, if so let's wait the CR update.

**Comment by theelk801** [comment]
you pay the actual costs after targeting but you choose whether you're going to pay those costs beforehand

**Comment by Susucre** [comment]
should be good now!

**Review by xenohedron — APPROVED** [review]

**Pull request merged**
