### PR TITLE
Implemented Yorion, Sky Nomad

### PR DESCRIPTION
**Pull request by theelk801**
I'm gonna need some other eyes on this one.

### CODE REVIEW

**Comment by theelk801** [comment]
just realized I forgot to implement the actual card, but that's not the part I was concerned about anyway

**Comment by emerald000** [comment]
Is it not possible to use DeckValidator.getDeckMinSize()?

**Comment by theelk801** [comment]
From what I could tell, I couldn't actually access that from within the Game class

**Comment by emerald000** [comment]
Looks like you are right. Seems fine to me in that case.

**Comment by JayDi85** [comment]
There are error in card's constructor (as example on new db create).

**Comment by theelk801** [comment]
No, that was a different card that I already fixed.

**Comment by theelk801** [comment]
I also just realized that this doesn't work for limited, but I'm not sure how to fix that.

**Comment by theelk801** [comment]
I think this should be good to go now.

**Pull request merged**
