### PR TITLE
Detection Tower and Witchbane Orb interaction bug confirmed for #5796

### PR DESCRIPTION
**Pull request by drmDev**
Tried to debug the issue, but for some reason when executing the test, it never hits the Detection Tower applies method with a breakpoint there. Either way, the test confirms the issue mentioned. I would guess its in the Detection Tower applies method with a conditional not checking on the opponent ID correctly:

### CODE REVIEW

**Comment by drmDev** [comment]
Even after the commit by @LevelX2  https://github.com/magefree/mage/commit/bf8dd78b6e1a33d404ad29d6808fbbec18cd6ff0  the unit test is failing. Is the issue really fixed? Is there an issue with the test?

**Comment by drmDev** [comment]
Figured it out - having both actions in the same phase was confusing it, or possibly the Shock was resolving first before hexproof was removed. UT passes now anyways.

**Comment by JayDi85** [comment]
You can also calls `waitStackResolved` between commands in the same step (example: `wait resolve(1, PhaseStep.PRECOMBAT_MAIN);`)

**Comment by drmDev** [comment]
Thanks for the tip!

**Pull request merged**
