### PR TITLE
spjspj - Add a version of Freeform Commander

### PR DESCRIPTION
**Pull request by spjspj**
Features: 
Any creature or legendary permanent can be commander
No ban list
Commander Partner restrictions retained
Color identity restrictions retained
Singleton restriction retained

The restriction to retain a legendary permanent (I don't know of any legendary instants/sorceries?) is required I think as things like hypergenesis as your commander would become who draws first wins.

### CODE REVIEW

**Comment by JayDi85** [comment]
>I don't know of any legendary instants/sorceries?

Who can be legendary: creature, planeswalker, artifact, enchantment, land.

You can [check it out on scryfall](https://scryfall.com/search?q=t%3Alegendary+-t%3Acreature+-t%3Aplaneswalker+-t%3Aartifact+-t%3Aland+-t%3Aenchantment) (remove or add `-t` mark to filter by type): 
 - search query: `t:legendary -t:creature -t:planeswalker -t:artifact -t:land -t:enchantment`

**Comment by Zzooouhh** [comment]
I should note here that if this gets implemented,  #4083 (or rather, the second half of the issue) should probably get addressed as to make Genju of the Realm playable as commander.

**Comment by theelk801** [comment]
I would think that this type of format would be a sort of catch-all for obscure commander where you can sort of do what you want, in which case you don't even bother with restrictions on commanders and let players just agree to it ahead of time.

**Comment by spjspj** [comment]
search query: t:legendary -t:creature -t:planeswalker -t:artifact -t:land -t:enchantment
^^ eww ;)

image

**Comment by spjspj** [comment]
@theelk801 I figured that creatures are  +1 on legendary creatures, and allowing other legendary cards would be ok.  It still kinds of keeps the restrictions and feel of commander but is less restrictive.  There's no established rules on the interwebs that I found whilst searching for it and I asked around relatively extensively in my network of players.

**Comment by theelk801** [comment]
The only thing I can think of is pauper commander, where you choose any uncommon creature as your commander.

**Comment by Zzooouhh** [comment]
TheElk has a point, the Nephilim and Tamanoa are some of the most popular "illegal" commanders, but neither is legendary.

**Comment by spjspj** [comment]
so, it is any creature or any legendary.

**Pull request merged**
