### PR TITLE
Add artifact type to token created by Canoptek Scarab Swarm

### PR DESCRIPTION
**Pull request by Susucre**
The card was not producing the proper kind of token. It is a token type generated only by that specific card.

### CODE REVIEW

**Comment by Susucre** [comment]
[[Canoptek Scarab Swarm]]

**Review by xenohedron — CHANGES_REQUESTED** [review]
The existing token isn't used anywhere else that I can see. It appears to have been added along with this card.

**Comment by JayDi85** [comment]
Any renames of token/emblem class names must be reflected in `tokens-database.txt` too:

shot_230826_143445

**Comment by Susucre** [comment]
Oh thanks, did not know about that!

**Review by xenohedron — APPROVED** [review]
I do think it would have been simpler to just add the artifact type to the existing token, but this is fine

**Pull request merged**
