### PR TITLE
Implemented Ancient Brontodon

### PR DESCRIPTION
**Pull request by caldover**

### CODE REVIEW

**Comment by theelk801** [comment]
Are you planning to implement more cards? If so, I can just leave this open while you add some more.

**Comment by caldover** [comment]
I didn't know I can do that. I'm looking through the list to see if I can do anything quick. Just doing this on my study break :)

**Comment by theelk801** [comment]
Don't sweat it, I'll just merge this one. But for future reference, you can do a single pull request for multiple commits.

**Comment by caldover** [comment]
Good to know, thanks!

**Pull request merged**
