### PR TITLE
MOM: Added card "Heliod, the Radiant Dawn" and its abilities and effects

### PR DESCRIPTION
**Pull request by Merlingilb**

### CODE REVIEW

**Comment by Merlingilb** [comment]
What am I doing wrong that the card back is not showing correctly?
The card seems to work perfectly but I cannot figure out why the back side is not showing.

heliod

**Comment by Merlingilb** [comment]
any suggestions?

**Comment by Merlingilb** [comment]
no one?

**Comment by JayDi85** [comment]
@Merlingilb update sources to latest version. Back side switch bug was fixed in last commits. You must delete `db` folder in `Mage.Client` to recreate db files. If not helps then try to download images from main menu. If not helps then report here.

**Comment by Merlingilb** [comment]
> @Merlingilb update sources to latest version. Back side switch bug was fixed in last commits. You must delete `db` folder in `Mage.Client` to recreate db files. If not helps then try to download images from main menu. If not helps then report here.

no, unfortunately that does not resolve the problem

**Comment by JayDi85** [comment]
Look at test errors. There are problems with miss `this.nightCard = true;` in `HeliodTheWarpedEclipse` class

**Comment by Merlingilb** [comment]
well reading the test logs would help...
works now

**Comment by theelk801** [comment]
thanks for the contribution

**Pull request merged**
