### PR TITLE
Added Hellhole Rats

### PR DESCRIPTION
**Pull request by DarrellBest**
I pulled this card from the requested list, but It would not let me sign in (I assume I need to have a username and password created for me) to claim the card. I will wait to see how you like this before I start on other cards.

### CODE REVIEW

**Comment by LevelX2** [comment]
Hello Darell, 

thanks for your contribution.
I added some comments.

It's important to test the cards, before you commit it to the repository.
Here some help for making testing easier.
https://github.com/magefree/mage/wiki/Developer-Testing-Tools

If you have any addional questions feel free to ask here or better in developer sub forum.

Regards 
LevelX2

**Comment by LevelX2** [comment]
If you want a profile for the card tracker (http://ct-magefree.rhcloud.com/) let me know where I can send the profile data to (email or PM in forum).

**Comment by LevelX2** [comment]
Will you try to fix the Hellhole Rats or shall I close the request?

**Comment by DarrellBest** [comment]
I would like to help but some of your comments do not make sense. I went through thirty plus cards that have already been implemented and coded with the style I saw. I am aware that some of the code may be old, but I need something more to go on. Any help would be appreciated.

**Comment by jeffwadsworth** [comment]
I will look at it.

**Pull request closed without merging**
