### PR TITLE
Impl The Beamtown Bullies

### PR DESCRIPTION
**Pull request by arketec**

### CODE REVIEW

**Comment by Grath** [comment]
[[The Beamtown Bullies]] has you choose the creature, not the opponent.

**Comment by arketec** [comment]
Ah yes, upon, re-parsing those words I understand it. That makes this card way better than I thought haha. fixed

**Comment by arketec** [comment]
original implementation also ignored the target part of "Target opponent". This has been changed to use target filters instead

**Comment by Alex-Vasile** [comment]
Thanks for the contribution

**Pull request merged**
