### PR TITLE
Implemented C19 Chainer, Nightmare Adept

### PR DESCRIPTION
**Pull request by goesta**
#5923

### CODE REVIEW

**Comment by JayDi85** [comment]
Please test that card -- is it can be activated second time (on next turn) or not? See issue #6001 for more details and workaround with post event instead reset.

**Comment by goesta** [comment]
It can be activated in each turn only once and this worked as expected in my tests.
But I just discovered that I can trigger the ability also in the opponents turn and discard a card. But as I can only cast in my main phase I can not cast a creature in the opponents turn.

I'm not shure what the expected behaviour actually should be. The card says once **each** turn so it may be the correct behaviour.

> Discard a card: You may cast a creature card from your graveyard this turn. Activate this ability only once each turn.
> Whenever a nontoken creature enters the battlefield under your control, if you didn’t cast it from your hand, it gains haste until your next turn.

**Comment by JayDi85** [comment]
Yes, you can activate that on any turn, that's correct.

**Comment by goesta** [comment]
But should I also be able to cast a creature on any turn?

**Comment by JayDi85** [comment]
Nope, it's [depends on card](https://scryfall.com/card/c19/39/chainer-nightmare-adept):

Chainer’s first ability doesn’t change when you can cast the creature card. You can normally only cast it during your turn while the stack is empty, but if the creature card has flash, you can cast it at other times. (2019-08-23)

**Comment by goesta** [comment]
Ok thank you :)

**Pull request merged**
