### PR TITLE
Add 18 new cards + change set package name

### PR DESCRIPTION
**Pull request by lunaskyrise**
Hi,
This is my first pull request, so I'm avid of comments and suggestions.
I especially request feedback on the implementation of Knollspine Invocation, as it's a bit hacky, to say the least.

Apart from the new cards, I adjusted the Tenth Edition's listing at Utils/known-sets.txt to match its package name.

### CODE REVIEW

**Comment by LevelX2** [comment]
Hello lunaskyrise,

thanks for you contribution. Overall your contribution looks very good.
Added some comments to the code yous should look into.

Please tell me if you have  an account on slightlymagic forum  (and what's the name) or give me an email adress, so I can add you to our (card tracker application)[http://ct-magefree.rhcloud.com/cards] and send you the profile data.
There you can mark the cards you are going to implement so no double development will happen.

Regards
LevelX2

**Comment by lunaskyrise** [comment]
Thanks for the comments,
I've applied the requested changes to Orcish Spy and Distorting Lens.
I've just rebased the pull request to pick up the changes for PutIntoGraveFromBattlefieldAllTriggeredAbility, but should the commits 7338022 to 1067ba2 appear here?

**Comment by LevelX2** [comment]
> PutIntoGraveFromBattlefieldAllTriggeredAbility, but should the commits 7338022 to 1067ba2 appear here?

Yeah, I guess that's normal.

**Comment by lunaskyrise** [comment]
I've applied all the corrections. Let me know if everything is ready so I correct the @{author}!

**Comment by LevelX2** [comment]
Looks good now. Thanks for your effords.

I merge it now because after some updating commits it's always a bit hard to check the sources of the pull request.
I'll take a final look at the classes tomorrow in the main repository.

**Comment by lunaskyrise** [comment]
About the card tracker: my account is amyluna, but I'm having a lot of trouble activating it (the mail never arrives).

**Comment by LevelX2** [comment]
> About the card tracker: my account is amyluna, but I'm having a lot of trouble activating it (the mail never arrives).
You can send a mail to admin to get your account activated.
http://www.slightlymagic.net/forum/viewtopic.php?f=110&t=15057&p=174990&hilit=Account+activation#p174990
I send you the card tracker profile data to amyluna.

**Pull request merged**
