### PR TITLE
Fix Path of Peril

### PR DESCRIPTION
**Pull request by thebear132**
[[Path of Peril]] said "less than 2", which only kills 1 drops. I changed it to "less than 3", so it also kills 2 drops.

### CODE REVIEW

**Comment by thebear132** [comment]
Hmm, i dont know why my merge commits is also put in the pull request. How do i make my Path of commit the only one submitted?

**Comment by thebear132** [comment]
> Hmm, i dont know why my merge commits is also put in the pull request. How do i make my Path of commit the only one submitted?

I should probably do the pull request from a branch. Im trying that, hold on

**Comment by Alex-Vasile** [comment]
> Hmm, i dont know why my merge commits is also put in the pull request. How do i make my Path of commit the only one submitted?

The merge commit is fine. When the PR is merged in they can all be squashed so that it shows up as a single commit with only the changes

**Comment by thebear132** [comment]
> > Hmm, i dont know why my merge commits is also put in the pull request. How do i make my Path of commit the only one submitted?
> 
> The merge commit is fine. When the PR is merged in they can all be squashed so that it shows up as a single commit with only the changes

Ok, but i can see my previous commit from like 2 days ago ("Added a missing reference to the Khans....")
That shouldnt be part of it tho?
I am now trying again, but commiting in a new branch dedicated to this Pull request. See if that works :)

**Comment by thebear132** [comment]
#8970 is the new one

**Pull request closed without merging**
