### PR TITLE
[AFR] Implementing dungeon mechanic (ready for review)

### PR DESCRIPTION
**Pull request by theelk801**
Current list of tasks:

- [x] create `Dungeon` class and `DungeonRoom` class
- [x] add triggered abilities for entering rooms
- [x] implement all the dungeons (only one so far but they're easy to add)
- [x] implement the actual venturing mechanic (abilities don’t appear on the stack but do function correctly)
- [x] handle when a dungeon is complete (kind of complicated, there are some weird stack things)
- [x] track whether a player has completed a dungeon and how many
- [ ] render ui (gonna need help with this one)
- [x] write many many tests

Mechanics article is [here](https://magic.wizards.com/en/articles/archive/feature/adventures-forgotten-realms-mechanics-2021-06-24), also various questions have been asked and answered [here](https://twitter.com/WotC_Matt/with_replies)

### CODE REVIEW

**Comment by theelk801** [comment]
Alright, venturing seems to be functioning correctly, but the trigger doesn’t appear on the stack. I’m gonna getting completing the dungeon done next, then write tests.

**Comment by JayDi85** [comment]
Don't forget about copy code. Current dungeon classes don't have it (e.g. rooms), so it must be broken on rollback, AI or in the middle of the game.

**Comment by theelk801** [comment]
yeah I just realized that

**Comment by JayDi85** [comment]
Also about missing completed coditional -- it must be same as `CitysBlessing` (e.g. activated until end of the game). From article:

> Note that Gloom Stalker doesn't have to be under your control as you complete the dungeon. It just shows up, takes one look at you, knows that you've completed a dungeon, and gives itself double strike. Game recognizes game.

**Comment by theelk801** [comment]
Yeah I know, I'm probably gonna have a watcher or something like that

**Comment by theelk801** [comment]
I copied `EmblemView` to make `DungeonView` and added it in all the same places, but room triggers still aren't showing up on the stack

**Comment by theelk801** [comment]
Alright, the two big issues I'm having right now is that the triggered abilities don't appear on the stack and the rooms aren't working if you venture in a different step/turn

**Comment by theelk801** [comment]
@JayDi85 I'm gonna merge this pretty soon, I've tested everything and it all works as expected. The UI isn't the best it could be and could definitely use more work in a future PR but it's completely functional and I want to get it done before previews start tomorrow.

**Pull request merged**
