### PR TITLE
Theme picker

### PR DESCRIPTION
**Pull request by dperegolise**
- Theme implementation complete with custom images for backgrounds, skip buttons, phase icons, win/defeat images, and custom colors for java swing components.
- Also includes a Preferences Dialog tab for theme selection. 
- Tested working on two computers via jar file sharing
- All background images are under 3MB
- None of the images can be guaranteed to be royalty/commercial-free. I'm not going to pick through each image and find a free alternative (insanely frustrating task), but what I can do is replace all images with solid color backgrounds if needed.
- Super insanely easy to implement new themes. Just add a new entry to ThemeType enum and fill out all the color values, which is very easy with intellij color picker. Then create theme folders in resources/background, /buttons, /phases, and /winloss. The time consuming portion is creating skip buttons and phase icons.
- This change increases the mage-client.jar by about 10MB
- examples: https://imgur.com/a/bc0zWVC

### CODE REVIEW

**Comment by dperegolise** [comment]
CI build failed due to failed test 'ThousandYearStormTest.test_GetControlNotCounts'

test_GetControlNotCounts **succeeds locally, and has the comment**: 
`// Test fails sometimes with the following message:
    // java.lang.AssertionError: b 0x copy after control - PlayerA have wrong life: 20 <> 17 expected:<17> but was:<20>
    @Test
    public void test_GetControlNotCounts() {`

**Comment by dperegolise** [comment]
replacing all images with free for commerical use images:

Backgrounds:
https://pixabay.com/photos/plouzane-lighthouse-france-landmark-1758197/
https://pixabay.com/vectors/triangles-polygon-color-pink-1430105/
https://pixabay.com/photos/christmas-advent-cinnamon-2918569/

Win/loss images:
https://pixabay.com/photos/blue-motivation-neon-lights-sign-1845901/
https://pixabay.com/illustrations/style-retro-futuristic-neon-figure-3411108/
https://pixabay.com/photos/coffee-pen-notebook-caffeine-cup-2306471/
https://pixabay.com/photos/background-bean-black-coffee-2847041/
https://pixabay.com/photos/dolphin-marine-mammals-water-sea-203875/
https://pixabay.com/photos/girl-sitting-jetty-docks-sad-1822702/

**Comment by 18ths** [comment]
This is impressive, great work! 

One thing that bothers me is that you treat default theme like its something special. I mean, you repeat the `if (this.currentTheme != ThemeType.DEFAULT) ` condition several times. For example, backgrounds. What if we wanted to add another theme that also does not have any background? That would require code change. All these special cases should be. If you get rid of those conditions, Its good to go for me (although I don't have merge rights ;))

**Comment by dperegolise** [comment]
@18ths see latest commit

- no more references to ThemeType.DEFAULT
- more enum values to specify which images are available making themes more configurable
- GREY theme created to showcase this
- all images (backgrounds, phase icons, etc) will check if current theme provides one, if not, fallback to default
- specify if skip shortcuts are visible for each theme (Usually F-keys)
- all colors are now mandatory for every theme
- custom user backgrounds are ALWAYS prioritized, fallback to theme backgrounds, fallback to default backgrounds.
- battle background implemented for coffee theme as showcase
- tested default theme, other themes, and custom user backgrounds
- all custom user backgrounds including battle bg, selected bg, and random bg tested working as higher priority than theme bgs

**Comment by dperegolise** [comment]
coffee battle bg: https://unsplash.com/photos/KugwNl9jX1Q

**Comment by dperegolise** [comment]
new coffee battle bg: https://unsplash.com/photos/sc1Eoqpr0sQ

**Comment by timhae** [comment]
Looks nice, maybe add a 'simple' Theme without any color and specific backgrounds? Also the menu looks a little strange for me, see [image](https://ibb.co/cw3NqHJ) plus I get
```
❯ mvn exec:java -Dexec.mainClass="mage.client.MageFrame"
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------< org.mage:mage-client >------------------------
[INFO] Building Mage Client 1.4.42
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ mage-client ---
INFO  2020-05-28 14:07:54,277 Starting MAGE client version 1.4.42V7 (build: runtime)                                     =>[mage.client.MageFrame.main()] MageFrame.main 
INFO  2020-05-28 14:07:54,279 Logging level: INFO                                                                        =>[mage.client.MageFrame.main()] MageFrame.main 
INFO  2020-05-28 14:07:55,922 Loading database...                                                                        =>[AWT-EventQueue-0] RepositoryUtil.bootstrapLocalDb 
INFO  2020-05-28 14:07:56,308 Loading symbols...                                                                         =>[AWT-EventQueue-0] ManaSymbols.loadImages 
INFO  2020-05-28 14:07:57,249 Loading plugins...                                                                         =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2020-05-28 14:07:57,279 [Game counter plugin, version 0.1] has been loaded.                                        =>[AWT-EventQueue-0] CounterPluginImpl.newPlugin 
INFO  2020-05-28 14:07:57,286 [Card plugin, version 0.7] has been loaded.                                                =>[AWT-EventQueue-0] CardPluginImpl.newPlugin 
INFO  2020-05-28 14:07:57,289 [Theme plugin, version 0.5] has been loaded.                                               =>[AWT-EventQueue-0] ThemePluginImpl.newPlugin 
INFO  2020-05-28 14:07:57,289 Done.                                                                                      =>[AWT-EventQueue-0] Plugins.loadPlugins 
INFO  2020-05-28 14:07:57,997 themeType: Island                                                                          =>[AWT-EventQueue-0] ImageManagerImpl.init 
WARN  2020-05-28 14:07:58,010 SystemTray is not supported                                                                =>[AWT-EventQueue-0] MageTray.install 
INFO  2020-05-28 14:07:58,078 Client start up time: 3 seconds                                                            =>[AWT-EventQueue-0] MageFrame.lambda$new$2 
[WARNING] 
java.lang.NullPointerException
    at com.sun.javafx.tk.quantum.QuantumToolkit.assignScreensAdapters (QuantumToolkit.java:695)
    at com.sun.javafx.tk.quantum.QuantumToolkit.notifyScreenListener (QuantumToolkit.java:700)
    at com.sun.javafx.tk.quantum.QuantumToolkit.access$000 (QuantumToolkit.java:136)
    at com.sun.javafx.tk.quantum.QuantumToolkit$4.handleSettingsChanged (QuantumToolkit.java:686)
    at com.sun.glass.ui.Screen.notifySettingsChanged (Screen.java:384)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop (Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11 (GtkApplication.java:277)
    at java.lang.Thread.run (Thread.java:834)
```
when building with OpenJDK11.

**Comment by dperegolise** [comment]
@18ths 
> As a side note, this can be also improved by reading the .yml config file containing theme configuration instead of putting the theme configuration in code. 

I agree that would be cool, but I like using the intellij color picker and honestly I don't think non-programmers are going to go hunting down rgb codes and royalty free backgrounds. If people are asking for this I can do it, just like 'dark mode'. But I don't want to keep dumping hours in until at least the base functionality gets merged in.

@timhae 
> Looks nice, maybe add a 'simple' Theme without any color and specific backgrounds? Also the menu looks a little strange for me, see image plus I get

I did, its the GREY theme. Also, idk why the menu looks like that for you. I build with jdk8. Running via intellij run config works fine for me, so does building the jar and dropping into mage-client/lib (and changing the META-INF classpath to use my build of mage-common due to changes in there from other devs). We'll see what happens when more people try to build this. I'm new to this code base and no clue why you're seeing that, but none of the changes I made should produce that.

Also that NPE doesn't seem to have anything to do with my changes either

**Comment by timhae** [comment]
@dperegolise I did not try to rebuild with JDK8 but that NPE is not related to your changes, you're right. Did you take a look at the implementation of the [theme plugin](https://github.com/magefree/mage/search?q=theme&unscoped_q=theme)? That seems to be integrated into the client already and could maybe used to facilitate your functionality as well.

**Comment by dperegolise** [comment]
> @dperegolise I did not try to rebuild with JDK8 but that NPE is not related to your changes, you're right. Did you take a look at the implementation of the [theme plugin](https://github.com/magefree/mage/search?q=theme&unscoped_q=theme)? That seems to be integrated into the client already and could maybe used to facilitate your functionality as well.

Yeah the 'theme plugin' should really be renamed to 'custom background impl', because its not a full theme implementation, nor is it really a plugin, its just a custom background setter built into the client. My theme implementation is backgrounds, colors, buttons, icons, etc like an actual theme. 

However, I made sure to stay out of the way of the 'theme plugin' so that users which want to set custom backgrounds can still do so, and they will take priority over backgrounds from my theme implementation. 

To follow up on how 'theme plugin' is not even really a plugin; Its loaded via `PluginManager.addPluginsFrom(new ClassURI(..))`, and bundled into the client jar (as opposed to loaded via `addPluginsFrom(new File(PLUGINS_DIRECTORY).toURI())` like counter plugin, so its not really an 'add-on' like a plugin should be, and its always loaded.

**Comment by 18ths** [comment]
Merged in PR #6755

**Comment by jeffwadsworth** [comment]
C:\mage\Mage.Client\src\main\java\mage\client\themes\ThemeType.java
This file has the color scheme for the current themes.

**Pull request closed without merging**
