### PR TITLE
Implement new way to generate boosters using box mapping info (WIP)

### PR DESCRIPTION
**Pull request by theelk801**
I'm not planning on finishing this any time soon but I wanted to at least get something started.

Connected to #6811

### CODE REVIEW

**Comment by theelk801** [comment]
here's the results of what I have so far, I generated packs using the old method and the new method

Old method:
old_packs

New method:
new_packs

honestly not sure how much of a difference it ends up making

**Comment by JayDi85** [comment]
Don't forget about comments in the source code with site link and data example (how-to use that).

**Comment by theelk801** [comment]
Yeah, planning on adding that.

**Comment by theelk801** [comment]
I still need to make this work with draft, not exactly sure how yet. I'd like to be able to make a separate collator for each individual draft.

**Comment by theelk801** [comment]
now that I think about it, it's fine for there to only be one shuffled version of the set at a time rather than having separate collators

**Comment by JayDi85** [comment]
1. Please, make to-do list what was done from lethe-website and what's can be done in the future. And put it to source code. 
2. Also it need info about implemented methods. Example: KHM have different run types from Japan and US/Belgium factory due to the website, but source don't have that remark. Another example: Sequential collation and Striped collation -- I think it must use definitions from the website too.

**Review by JayDi85 — APPROVED** [review]
Code looks fine.

**Comment by theelk801** [comment]
Alright, I'll add more comments and then merge

**Comment by theelk801** [comment]
By the way, do you have logs from the server about what sets are being drafted besides the most recent ones?

**Comment by JayDi85** [comment]
Nope, server do not collect game mode and draft stats (used sets, picks, etc). It have only rating related stats like games, players and winners/losers.

**Comment by theelk801** [comment]
alright then, just wanted an idea of whether there were older sets that people drafted a lot which could be improved

**Comment by JayDi85** [comment]
Hmm, found booster info in the server records. I'll look later.

**Comment by theelk801** [comment]
awesome, thanks

**Pull request merged**
