### PR TITLE
Allows custom binding of keys in game mode

### PR DESCRIPTION
**Pull request by ZNixian**
Allows the user to change the keybindings for different shortcuts available while playing. This adds a controls tab to settings, and draws the key text onto the control buttons.

### CODE REVIEW

**Comment by digitalDojoNZ** [comment]
Kai pai!

**Comment by LevelX2** [comment]
Thanks for your contribution.

**Comment by LevelX2** [comment]
Nice addition.
Maybe you can add still two things:
1) If I set a KEY, that is already used for other actions, set these other actions to Key = nothing.
2) In the preferences a button that resets the controls back to the default values.

**Comment by ZNixian** [comment]
OK, I'll add those

**Pull request merged**
