### PR TITLE
Implement Heartstone

### PR DESCRIPTION
**Pull request by pcasaretto**
Hey guys,

My first PR here. Is there something I can do to improve it?

### CODE REVIEW

**Comment by pcasaretto** [comment]
Done @LevelX2 !
An oversight from copying over Training Grounds.

**Comment by LevelX2** [comment]
Thanks for your contribution.

**Comment by pcasaretto** [comment]
BTW @LevelX2 when will this be available?
I ask because I noticed Amoeboid Changeling is already implemented but I cant use it.

**Comment by LevelX2** [comment]
I guess probably during the coming week latest on the next weekend.

**Pull request merged**
