### PR TITLE
Add new deck type European Highlander

### PR DESCRIPTION
**Pull request by ddzn**
Adding support for European Highlander Decks.
This change enables deck validation and duels in this format.
More info at http://highlandermagic.info.

### CODE REVIEW

**Comment by ddzn** [comment]
I am a new contributor. Please feel free to point out any conventions I violated.
Thanks!

**Comment by ddzn** [comment]
Browsing the issues I just discovered there was a feature request for "German Highlander" which is the previous/alternative name for this format: #6302

**Comment by ddzn** [comment]
Guys, this PR is now 6 days old and 102 commits behind master. Should I rebase it to head?

**Comment by JayDi85** [comment]
Nope, it will be done on PRs merge.

**Comment by ddzn** [comment]
Did my PR come at a bad time or is it just a boring topic to review? :)

**Comment by JayDi85** [comment]
@ddzn nope. There is an mtg release, so it slower for non critical PRs. Just wait your time.

**Comment by ddzn** [comment]
Thanks for the heads up

**Pull request merged**
