### PR TITLE
Added a few cards

### PR DESCRIPTION
**Pull request by laxika**
My first cards ever contributed. I'll do more in the future.

### CODE REVIEW

**Comment by LevelX2** [comment]
Hello,

thanks for your contribution.
Did you use the latest gen-card.pl script?
Becuase I removed the set color code generation some time ago and your cards did include the color setting.

The classes look good overall. Implement the small indicated changes and I'm going to merge the cards into the main repository.

Do you have a profile in slightlymagic forum you can inform me about (or an email adress)? So I will give you profile information for our [card tracking system](http://ct-magefree.rhcloud.com/). There you can indicate cards you are going to implement to prevent double implementation.

Regards

**Comment by laxika** [comment]
Hello!

I picked cards that had a similar card already implemented and used that card as the base for the new card. I made Fishliver Oil out of Burrowing for example. (I was lazy enough not to set up the card generator script. :S)

I'm trying to figure out the different Abilities but there are no much documentation (Javadoc or tests) about them so it's a bit tough. This is the good way?:

```
// Enchanted creature has islandwalk.
Ability islandwalkAbility = new SimpleStaticAbility(Zone.BATTLEFIELD, new GainAbilityAttachedEffect(new IslandwalkAbility(), AttachmentType.AURA));
this.addAbility(islandwalkAbility);
```

Also why Islandwalk is not a singleton like every other Ability?

Also I set up everything on the laptop I use at works so I can only dev on weekends. I don't want to get access to the card tracking system yet because I have limited free time/knowledge at the moment. When I'll be good enough I'll request access from you. If I develop something that already done thats no problem. I'm doing this for learning purposes at the moment.

**Comment by LevelX2** [comment]
Using the card generator script is a thing you will like a lot if you use it. So I recommend to use it, it also helps a lot to reduce typo errors.

You'r right, not all cards use always the best/latest way to do a specific thing.
Common sequence is that at some point, if an effect or ability is needed more than a very small number of times (like more than 3 times), we often create a common framework ability/effect to handle a specific demand. But not always all old cards are updated with a newer technique. So in this case you used Burrowing to copy and that was not changed. It's always a good thing to check more than one card with similar handling to check, if all are done the same way or if already some different ways are implemented.

Not all abilities are done as Singletons, I would say the very majority of abilities is not done as Singletons. Concerning landwalk abilities I guess it would be possible to do it also as a Singleton. But I'm not sure if it would be the better way. We had a lot of problems with Singletons in the past, but I hope this bugs are fixed now. So it's a sometimes a historical cause how something is done. 

For giving islandwalk to the enchanted creature your proposal is correct but you can a bit more simple use:
```
this.addAbility(new SimpleStaticAbility(Zone.BATTLEFIELD, 
         new GainAbilityAttachedEffect(new IslandwalkAbility(), AttachmentType.AURA)));
```

**Comment by laxika** [comment]
First of all, thanks for the detailed reply!

I'll use the generator script next time. Last weekend I was happy to set up the IDE and just wanted to try out my coding skills on the cards asap. (It took me a few hours to set up everything correctly.)

Well I don't really like the singleton pattern at all, and I'm aware that it can lead to a lot of bugs when misused. I just wanted to know why some abilities use Singletons and others don't. Also I see that card code getting older and older and not always use the best implementation. Next time I'll be more aware of that and check out more similar cards. Also I'll update Burrowing to todays standards too.

Can't wait until next weekend. :)

**Comment by LevelX2** [comment]
I merge this and check it in the repository.

**Pull request merged**
