### PR TITLE
Refactored TargetController predicates

### PR DESCRIPTION
**Pull request by theelk801**

### CODE REVIEW

**Comment by JayDi85** [comment]
```
this.damagedPlayerThisTurnPredicate = new DamagedPlayerThisTurnPredicate(this);
```

Don't add rare predicates to classes. It's bloats the code. Also don't create all possible predicates in TargetController usage (it's enum and generate new objects on every operations/moves, but you need only one in rare calls -- it's can be null by default with lazy init on needs).

**Comment by theelk801** [comment]
Yeah, sounds good.

**Comment by JayDi85** [comment]
@theelk801 I was wrong with lazy loading -- it's not necessary, enum uses one instance all the time. You must create all predicates at constructor.

**Comment by theelk801** [comment]
yeah that's what I thought, I'll change it back

**Pull request merged**
