### PR TITLE
[GUI] Add Token on type line.

### PR DESCRIPTION
**Pull request by Susucre**
Minor tweak on the ModernCardRenderer: add Token (or T. if not enough space) in front of the type line, in order to differentiate (altough subtle) tokens from non-tokens.

image
image

### CODE REVIEW

**Review by xenohedron — APPROVED** [review]
Makes sense to me

**Comment by xenohedron** [comment]
btw some of those type lines say "Creature Artifact", that should be fixed to "Artifact Creature" right?

**Comment by Susucre** [comment]
Oh right, Supertypes/Types are alphabetically sorted. e.g. https://scryfall.com/search?q=Is%3Atoken+t%3Acreature+t%3Aenchantment&unique=cards&as=grid&order=name
Not sure Subtypes are or should be. https://scryfall.com/card/who/3/the-tenth-doctor

**Comment by Susucre** [comment]
Arg Tribal is printed before Instant. https://scryfall.com/card/mm2/105/blades-of-velis-vel

**Comment by xenohedron** [comment]
I just fixed ~20 tokens in 9eca83d (using find replace after correcting one example)

**Pull request merged**
