### PR TITLE
Implemented PowerArtifact.java

### PR DESCRIPTION
**Pull request by myersn024**

### CODE REVIEW

**Comment by myersn024** [comment]
Made the necessary changes.

**Comment by LevelX2** [comment]
I fixed the import definitions for PowerArtifact.

**Comment by myersn024** [comment]
I always forget to remove the unused imports once I've made changes. I'll try to do better about remember to take those out.

**Comment by fireshoes** [comment]
I've been using right-click Fix Imports a lot recently. It will clear all of the unused imports.

**Comment by jeffwadsworth** [comment]
That and Format work quite well to tidy things up.

**Comment by LevelX2** [comment]
In netbeans I'm using SHIFT + CTRL + i to correct the imports.
But it''s still easy to forget unused imports.

But in this case also an import was missing, that's shown as error in netbeans editor with a red marker, also marking the object in the project tree.

@myersn024 
So I wonder how you were not aware of the missing import?
Don't you use netbeans or do you have switched off the import checking?

**Comment by myersn024** [comment]
I was away from my primary development machine, so instead of pushing the
change to my fork (since there are several unfinished cards on the computer
I was using) I just manually edited the file in GitHub.

**Comment by LevelX2** [comment]
> I was away from my primary development machine, so instead of pushing the change to my fork (since there are several unfinished cards on the computer I was using) I just manually edited the file in GitHub.

ok, that explains it. I only wanted to be sure that you are aware of the existing tools to help with these things :-) .

**Pull request merged**
