### PR TITLE
Implementations for Fertilid, Pain Magnification, Aquitect's Will, and Elvish Berserker

### PR DESCRIPTION
**Pull request by ilcartographer**

### CODE REVIEW

**Comment by ilcartographer** [comment]
Going to fix an issue in Aquitect's Will and re-open

**Comment by ilcartographer** [comment]
Wasn't sure if there's a better way for Aquitect's Will to handle retaining the other land types, but I tested this on a normal Forest and on a Temple Garden and had the expected results

**Comment by LevelX2** [comment]
I took a short check for the cards and did some minor updates.
Maybe you check out.
9f7ce41679127609f7a1c7ae6b4036572db98601

**Comment by ilcartographer** [comment]
Everything looks great, wasn't aware about some of that stuff, but that's helpful, thanks!

**Pull request merged**
