### PR TITLE
[DMC] Implement Orca, Siege Demon

### PR DESCRIPTION
**Pull request by PurpleCrowbar**

### CODE REVIEW

**Comment by PurpleCrowbar** [comment]
[[Orca, Siege Demon]]

**Comment by awjackson** [comment]
I think you should be able to implement the dies triggered ability using `DamageMultiEffect` rather than a custom target adjuster and custom effect. See [[Volcanic Wind]] for an example of `DamageMultiEffect` with a `DynamicValue` damage/target amount.

**Comment by PurpleCrowbar** [comment]
> I think you should be able to implement the dies triggered ability using `DamageMultiEffect` rather than a custom target adjuster and custom effect. See [[Volcanic Wind]] for an example of `DamageMultiEffect` with a `DynamicValue` damage/target amount.

Tried changing the ability to:
```
Ability ability = new DiesSourceTriggeredAbility(new DamageMultiEffect(this.getPower().getValue())
        .setText("When {this} dies, it deals damage equal to its power divided as you choose among any number of targets."));
ability.addTarget(new TargetAnyTargetAmount(this.getPower().getValue()));
this.addAbility(ability);
```
But `this.getPower().getValue()` only gets the base value (5, in this case) regardless of the number of +1/+1 counters on Orca. Not sure if it's checking the card's stats when it's in the graveyard or something

**Comment by Alex-Vasile** [comment]
> > I think you should be able to implement the dies triggered ability using `DamageMultiEffect` rather than a custom target adjuster and custom effect. See [[Volcanic Wind]] for an example of `DamageMultiEffect` with a `DynamicValue` damage/target amount.
> 
> Tried changing the ability to:
> 
> ```
> Ability ability = new DiesSourceTriggeredAbility(new DamageMultiEffect(this.getPower().getValue())
>         .setText("When {this} dies, it deals damage equal to its power divided as you choose among any number of targets."));
> ability.addTarget(new TargetAnyTargetAmount(this.getPower().getValue()));
> this.addAbility(ability);
> ```
> 
> But `this.getPower().getValue()` only gets the base value (5, in this case) regardless of the number of +1/+1 counters on Orca. Not sure if it's checking the card's stats when it's in the graveyard or something

`this.getPower().getValue()` is not going to work. It will return an integer the moment it gets evaluated (at the time of the card's creation).

Look at [[Juri, Master of the Revue]] and `SourcePermanentPowerCount`

**Comment by PurpleCrowbar** [comment]
`SourcePermanentPowerCount` was the way to go, thanks

**Review by Alex-Vasile — APPROVED** [review]

**Review by awjackson — APPROVED** [review]

**Pull request merged**
