### PR TITLE
Converted cardNumber from int to String. Now card number with "a" or "b" can be used.

### PR DESCRIPTION
**Pull request by fwannmacher**
- Converted CardImpl.cardNumber from int to String
- Fixed Issue #1953 
- Fixed Issue #1914
- Fixed Issue #739

### CODE REVIEW

**Comment by drmDev** [comment]
Thanks for your contributions. I'm a little hesitant on the Card Number changes but the rest of the fixes look good.

**Comment by fwannmacher** [comment]
I tested those changes a lot. I know it's huge, but I'm confident everything is working.

**Comment by drmDev** [comment]
I took your word for it and merged them in. There are some build issues with some cards that were added fairly recently. I should have those fixed momentarily and confirm with a full clean build. We may need to make slight adjustments in some of our utility scripts to correctly handle this change - most noteable gen-card.pl .

**Comment by fwannmacher** [comment]
I didn't know about those scripts. And yes, if a card was added after I've done the fork, surely they will break the build.

Where can I find those scripts?

**Comment by drmDev** [comment]
In the Mage.Utils directory you'll find them. You can read about them in the wiki: https://github.com/magefree/mage/wiki/Developer-Getting-Started#perl

The gen-card.pl script there is used to generate the base card templates when creating new cards - greatly speeds up the process and reduces errors from manual input. I haven't spent too much time looking at the inner workings of the script, but as far as I can tell we just need to add quotes around this.cardNumber property in the cardExtendedClass.tmpl:

`this.cardNumber = "[=$cardNumber=]";`

Not a big deal, just thinking of anything else we may need to factor in with these changes.

**Comment by fwannmacher** [comment]
Do you will fix the new cards? While you do that, I can fix the scripts.

**Comment by drmDev** [comment]
There was only one card to fix and it's in master already. We're set there. I'm just going through the Mage.Tests project now to confirm the tests are passing now.

**Comment by fwannmacher** [comment]
If something goes weird, let me know.

**Comment by fwannmacher** [comment]
About the scripts, the only one that needs to  be changed is cardExtendedClass.tmpl, because I've created contructors those accept int as cardNumber and convert them to String.

**Pull request merged**
