### PR TITLE
Address #8742 - Reflection of Kiki-Jiki token being sacrificed incorrectly

### PR DESCRIPTION
**Pull request by Grath**
Hopefully this fixes the entire problem with #8742 with the exchange being undone, but at a minimum you can't sacrifice a token that your opponent controls.

### CODE REVIEW

**Comment by Alex-Vasile** [comment]
Can you please include a test for the case you are solving from the referenced issue?

**Comment by Grath** [comment]
I finally got it set up to where I can try testing it, but the test refuses to cooperate. This corrected behavior of SacrificeTarget is successfully tested in https://github.com/magefree/mage/blob/master/Mage.Tests/src/test/java/org/mage/test/cards/copy/KikiJikiMirrorBreakerTest.java though.

**Comment by Alex-Vasile** [comment]
> I finally got it set up to where I can try testing it, but the test refuses to cooperate. This corrected behavior of SacrificeTarget is successfully tested in https://github.com/magefree/mage/blob/master/Mage.Tests/src/test/java/org/mage/test/cards/copy/KikiJikiMirrorBreakerTest.java though.

There is a test there for this `testTokenNotSacrificedIfNotControlled()` but it doesn't seem to be working properly. Instead of Gilded drake it uses a Humble defector, but the outcome should be the same. Humble defector should have the same problem (i.e. get sacrificed even though it was under other player's control). But that test is currently passing, even though it shouldn't.

**Comment by Alex-Vasile** [comment]
What are you having trouble with in terms of the tests?

**Comment by Grath** [comment]
> > I finally got it set up to where I can try testing it, but the test refuses to cooperate. This corrected behavior of SacrificeTarget is successfully tested in https://github.com/magefree/mage/blob/master/Mage.Tests/src/test/java/org/mage/test/cards/copy/KikiJikiMirrorBreakerTest.java though.
> 
> There is a test there for this `testTokenNotSacrificedIfNotControlled()` but it doesn't seem to be working properly. Instead of Gilded drake it uses a Humble defector, but the outcome should be the same. Humble defector should have the same problem (i.e. get sacrificed even though it was under other player's control). But that test is currently passing, even though it shouldn't.

Kiki-Jiki was coded correctly. Reflection of Kiki-Jiki wasn't, this change brings the implementation in line with Kiki-Jiki.

Turns out the problem with the test was that I was giving the wrong player a land; I just used Humble Defector again rather than messing with Gilded Drake, but this still tests that this change addresses the clearly broken functionality.

**Comment by Alex-Vasile** [comment]
> > > I finally got it set up to where I can try testing it, but the test refuses to cooperate. This corrected behavior of SacrificeTarget is successfully tested in https://github.com/magefree/mage/blob/master/Mage.Tests/src/test/java/org/mage/test/cards/copy/KikiJikiMirrorBreakerTest.java though.
> > 
> > 
> > There is a test there for this `testTokenNotSacrificedIfNotControlled()` but it doesn't seem to be working properly. Instead of Gilded drake it uses a Humble defector, but the outcome should be the same. Humble defector should have the same problem (i.e. get sacrificed even though it was under other player's control). But that test is currently passing, even though it shouldn't.
> 
> Kiki-Jiki was coded correctly. Reflection of Kiki-Jiki wasn't, this change brings the implementation in line with Kiki-Jiki.
> 
> Turns out the problem with the test was that I was giving the wrong player a land; I just used Humble Defector again rather than messing with Gilded Drake, but this still tests that this change addresses the clearly broken functionality.

Yeah, my bad earlier. I had assumed that the two cards used the same implementation, but if I look at them, they are using quite different implementations for their effects. Which seems strange to me given that they're identical effects.

That being said, the fix in the PR is definitely needed since the other cards using would also have the same issue.

**Comment by Grath** [comment]
Anyways, the fix that this PR is implementing is now tested as well. It should also fix whatever weird situation was going on with undoing the swap that the old version of the code was doing, since the Gilded Drake token no longer sacrifices at end of turn.

**Comment by Alex-Vasile** [comment]
Thanks for the contribution!

**Pull request merged**
