### PR TITLE
add import support for mtgjson deck files

### PR DESCRIPTION
**Pull request by timhae**
please do not hesitate to comment/provide feedback

### CODE REVIEW

**Comment by timhae** [comment]
implement feature request from issue #6475

**Comment by JayDi85** [comment]
MTGJson decks is set depended -- e.g. it contains info about card names with set code. It will be good to search cards by set first (if no card name in set then search by name only).

There are already implemented `lookupCardInfo` method with CardCriteria param.

shot_200429_172212

**Comment by timhae** [comment]
I updated the lookup accordingly. It automatically handles all cases (card not found in set/empty set string) as far as I can tell.

One other question: is there a general codestyle I shoud adhere to? The tests are using two spaces to indent and the other files four. I am not an advocat for either but I think it should be the same :)

**Comment by JayDi85** [comment]
Preferred code style: default IntelliJ style for code and import format (CTRL+O, CTRL+L).

P.S. Four spaces.

**Comment by timhae** [comment]
Thanks! I am working with vim but I guess there is a plugin for that.. :)

**Comment by JayDi85** [comment]
Thanks for PR.

**Pull request merged**
