### PR TITLE
Implemented Commander Centurion Banlist and Rules

### PR DESCRIPTION
**Pull request by andreacosta**
Implemented Commander Centurion (Italian version of Duel Commander) with rules and banlist (#6014 )

### CODE REVIEW

**Comment by theelk801** [comment]
This format has banned partners as well, I've pushed a change to the base `Commander` class to allow this.

**Comment by andreacosta** [comment]
I don't use a lot Github, what i must to do now? Update the code in my repo and create a new pull request?

**Comment by theelk801** [comment]
You can just commit the changes and push them, the pull request will synchronize automatically.

**Comment by andreacosta** [comment]
ok thanks, i'll do it soon

**Comment by andreacosta** [comment]
Done

**Comment by theelk801** [comment]
Looks like you committed checkpoint files. What IDE are you using?

**Comment by andreacosta** [comment]
Visual Studio Code

**Comment by theelk801** [comment]
Oh I see, looks like no one else has used that IDE so the gitignore doesn't have `.history`. Can you delete those files and commit? I'll update the gitignore.

**Comment by andreacosta** [comment]
Done... now is ok?

**Comment by theelk801** [comment]
Yeah, looks good. Thanks for the contribution.

**Comment by andreacosta** [comment]
Thanks you for the help.

**Comment by andreacosta** [comment]
When new release will be release? Me and my friend would test our Centurion Deck with xMage :)

**Comment by JayDi85** [comment]
@andreacosta I'v updated [beta client](http://xmage.today/) to newest version. You try it to test.

**Comment by andreacosta** [comment]
@JayDi85 i would try the new version but there is an error:
my client version is 1.4.39V1 but the server has 1.4.39V0, is possible update the server?

**Comment by JayDi85** [comment]
You must connect to beta.xmage.today server, not de or us.

**Pull request merged**
