### PR TITLE
Correct the mana cost of Ixidor, Reality Sculptor

### PR DESCRIPTION
**Pull request by jovalec**
Wrong value caused a corresponding test to fail

### CODE REVIEW

**Comment by jovalec** [comment]
Should `/Utils/mtg-cards-data.txt` be updated too?

**Comment by LevelX2** [comment]
> Should /Utils/mtg-cards-data.txt be updated too?

Wouldn't be a mistake.

**Comment by LevelX2** [comment]
Thanks for your contribution.

**Comment by fireshoes** [comment]
I got the .txt file update.

**Pull request merged**
