### PR TITLE
Implemented some more Invasion Cards

### PR DESCRIPTION
**Pull request by mnapoleon**
This pull request completes the following cards from the Invasion set....
Stun (also in Tenth and Tempest)
Capashen Unicorn
Firescreamer
Crusading Knight
Marauding Knight

(sorry for the numerous commits here.  I was working on numerous machines and committing and pushing to my fork to keep updated)

### CODE REVIEW

**Comment by LevelX2** [comment]
Color predicates of the knights protection filters are missing.
author not always set.

**Comment by mnapoleon** [comment]
Whoops.  I'll fix the knights.  Not sure how I missed that

**Comment by LevelX2** [comment]
That happens all the times. Humans are not perfect. :-)
Always if I look over an old source I created/changed I find things to fix or at least to improve.

**Comment by mnapoleon** [comment]
color predicates have been fixed.

**Pull request merged**
